### ISSUE TITLE
error with commit f888a03

### ISSUE THREAD

**Issue by ppascher** [Cloudef/bemenu#100]
building and starting with commit #99 causes the following error for me:

`./bemenu-run: error while loading shared libraries: --library=gcc: cannot open shared object file: No such file or directory`

```
ldd /usr/local/bin/bemenu
	linux-vdso.so.1 (0x00007ffc697ef000)
	--library=gcc => not found
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f5990209000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f5990411000)
```

**Comment by Earnestly** [comment]
Heh, I get the same output with `ldd` but `bemenu` (and `bemenu-run`) work regardless.

```
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [--library=gcc]
```

It seems like `-soname` takes an argument but one wasn't provided.

**Comment by ppascher** [comment]
You are right, seems to be not correctly set. For me neither bemenu nor bemenu-run work though:

```
objdump -p /libbemenu.so
...
SONAME               --library=gcc
...
```

**Comment by Cloudef** [comment]
Does giving the `-soname` argument `$(addsuffix .$(firstword $(subst ., ,$(VERSION)))` work as expected? E.g. ldd / objdump should say it's using the `libbemenu.so.MAJOR`. (I hate dynamic libraries)

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/fdcf8e9b3908b6362aa8b7faabf573eb5415f342
Should be fixed by this

**Comment by Cloudef** [comment]
Just some offtopic:
I'm not sure why people want soname at all.. It basically breaks the ability to link into the specific library version. There's already 3 symlinks provided for different usecase. Link against libbemenu.so, if you don't care about which version of bemenu is installed on the system (most likely to break your application on major version bumbs). Link against libbemenu.so.MAJOR and your application will work as long as the same MAJOR version of bemenu exists in the system (MAJOR usually guarantees ABI compatibility). Link against libbemenu.so.MAJOR.MINOR.PATCH and you will only allow that specific version of the library. It's not that I'm particularly fond of static libraries at all either though.. but they do work all right for things like pluggable features which could also be offered by offering separate binaries/libraries, or through IPC I guess.
