### ISSUE TITLE
Command-line arguments for colour has no effect.

### ISSUE THREAD

**Issue by Earnestly** [Cloudef/bemenu#11]
This is mostly for tracking.

**Comment by Cloudef** [comment]
bemenu-run --nb "#444444" --tb "#FFFFFF" --fb "#555555" seems to work fine here.

**Comment by Earnestly** [comment]
Ah, it changed?  I was using:
```
    --nf '#a7a7a7' --nb '#1e1e1e'
    --sf '#9b859d' --sb '#262626'
```
which doesn't cause any errors but doesn't set the colours corresponding.

**Comment by Cloudef** [comment]
You probably went highlight color instead of selection color, right?

**Comment by Earnestly** [comment]
Yup, there was confusion between dmenu's command-line options and the assumption of `--bg` being ineffectual as an issue for the rest.

Fixed by using `--hf` and `--hb` instead.
