### ISSUE TITLE
Can't work without specifying BEMENU_RENDERERS

### ISSUE THREAD

**Issue by Eluminae** [Cloudef/bemenu#110]
Hello ! I'm trying to upgrade bemenu from 0.3.0 to 0.4.1 on VoidLinux. I moved to gnu-makefile and I builded this package

```
sudo xbps-query -f bemenu
/usr/bin/bemenu
/usr/bin/bemenu-run
/usr/lib/bemenu/bemenu-renderer-curses.so
/usr/lib/bemenu/bemenu-renderer-wayland.so
/usr/lib/bemenu/bemenu-renderer-x11.so
/usr/lib/libbemenu.so.0.4.1
/usr/lib/pkgconfig/bemenu.pc
/usr/share/man/man1/bemenu-run.1
/usr/share/man/man1/bemenu.1
/usr/lib/libbemenu.so.0 -> /usr/lib/libbemenu.so.0.4.1
```

The thing is, nothing happen when using bemenu or bemenu-run unless I specify `BEMENU_RENDERERS=/usr/lib/bemenu/`

Why ? Is there something wrong ?

**Comment by Eluminae** [comment]
My WIP package upgrade here: https://github.com/void-linux/void-packages/pull/21111

**Comment by Earnestly** [comment]
Does the template use `make PREFIX=/usr` during the build as well as the install?

**Comment by Eluminae** [comment]
The void-package manual says:

> configure_args The arguments to be passed in to the configure script if ${build_style} is set to configure or gnu-configure build methods. By default, prefix must be set to /usr. In gnu-configure packages, some options are already set by default: --prefix=/usr --sysconfdir=/etc --infodir=/usr/share/info --mandir=/usr/share/man --localstatedir=/var

I guess this prefix is used yes

**Comment by Eluminae** [comment]
Oh wait, I am using `gnu-makefile` so probably no

**Comment by Eluminae** [comment]
Okay I fixed it !

I mistaked the gnu-configure and the gnu-make in my last note but anyway:

`make_install_args` use `PREFIX=/usr` by default but `make_build_args` dont. I just setup this variable and now the package is working.

Ty for the goot tip :D

**Comment by Eluminae** [comment]
And thanks for the amazing work. With those new releases I am now totally leaving dmenu for bemenu thanks to the configuration env and the compatibility X11/Wayland. <3
