### ISSUE TITLE
Spacing in single-line mode

### ISSUE THREAD

**Issue by siiptuo** [Cloudef/bemenu#113]
I think that spacing between items in single-line mode is too small. For example, using text "hello world" the space between "o" and "w" is larger than the space between items:

![image](https://user-images.githubusercontent.com/10729330/79746818-4a286500-8313-11ea-9dcc-52ee5d18b7dc.png)

This makes it hard to see where the item starts and stops. I suggest that either:

- make the padding bigger like in `dmenu`, or
- make the padding configurable like `bemenu -H`.

Also, the text not centered horizontally (apparent when using a background color):

![image](https://user-images.githubusercontent.com/10729330/79746841-53b1cd00-8313-11ea-9d37-aa7096a93c66.png)

Here's a quick fix for these issues:

```diff
diff --git a/lib/renderers/cairo.h b/lib/renderers/cairo.h
index 07eaa55..b9b3032 100644
--- a/lib/renderers/cairo.h
+++ b/lib/renderers/cairo.h
@@ -361,10 +361,11 @@ bm_cairo_paint(struct cairo *cairo, uint32_t width, uint32_t max_height, const s
                 bm_cairo_color_from_menu_color(menu, BM_COLOR_ITEM_BG, &paint.bg);
             }

+            int32_t hpadding = 4;
             paint.pos = (struct pos){ cl, vpadding };
-            paint.box = (struct box){ 2, 4, vpadding, vpadding, 0, ascii_height };
+            paint.box = (struct box){ hpadding / 2, 1.5 * hpadding, vpadding, vpadding, 0, ascii_height };
             bm_cairo_draw_line(cairo, &paint, &result, "%s", (items[i]->text ? items[i]->text : ""));
-            cl += result.x_advance + 2;
+            cl += result.x_advance + 0.5 * hpadding;
             out_result->displayed += (cl < width);
             out_result->height = fmax(out_result->height, result.height);
         }
```

It seems that `box.lx` is applied both in the rectangle and text positions. Is this a bug?

**Comment by Cloudef** [comment]
IIRC when drawing boxes there are also "margin" supplied in, so the `box.lx` should be fine.
Bemenu is supposed to look and behave identical to dmenu as possible by default, so patch to make the spacing more like in dmenu is welcome.

**Comment by siiptuo** [comment]
> IIRC when drawing boxes there is also "margin" supplied in, so the `box.lx` should be fine.

I was just wondering because the above patch seems more complicated than necessary. I would expect `hpadding, hpadding, vpadding, vpadding` (or original `hpadding, 2*hpadding, vpadding, vpadding`) to center the text.

> Do you want me to apply the above diff manually? Or will you do a PR?

Currently the arrows are not taken into account. I can make a PR later.

**Comment by Cloudef** [comment]
I was just wondering because the above patch seems more complicated than
necessary. I would expect

It could be the draw_line or draw_text function is buggy.

**Comment by notramo** [comment]
Is there any progress on this?

**Comment by lokesh-krishna** [comment]
If the patch works as it is then can I make a PR?
