### ISSUE TITLE
No options after building

### ISSUE THREAD

**Issue by yellowhat** [Cloudef/bemenu#119]
Hi,
if I try to build from scratch:
```
git clone https://github.com/Cloudef/bemenu
cd bemenu
make clients wayland
```
It compiles without any problem.

If I try to run the generated executable, even to see the help:
```
./bemenu --help
```
nothing is returned.
Same problem with 0.4.0 and 0.4.1.

I am using gentoo-testing with gcc-10.1.

Any ideas?

Thanks

**Comment by Cloudef** [comment]
DId you read this bit from the README?
># To test from source, you have to point the LD_LIBRARY_PATH and BEMENU_RENDERERS variables:
>LD_LIBRARY_PATH=. BEMENU_RENDERERS=. ./bemenu-run

**Comment by yellowhat** [comment]
Sorry, thank you very much.
