### ISSUE TITLE
bemenu-run now displaying cursor

### ISSUE THREAD

**Issue by guinanseyebrows** [Cloudef/bemenu#120]
Before the last update, bemenu-run did not display a cursor block. Now it's displaying an intrusive cursor block that takes up the entire line height that seems to take its color information from --nf/--nb. 

![bemenu-cursor](https://user-images.githubusercontent.com/12642404/81743062-c149a880-943c-11ea-83d1-e471da59c7ca.png)

Was this an intentional change, and if so, could we get an option to either hide the cursor or provide separate color information (so it can appear hidden by matching the background color)?

Otherwise if there's something else I'm doing wrong, I'd appreciate a pointer in the right direction. I'm on Arch using x11. Here's what I run to invoke bemenu-run:
```
bemenu-run \
        -p ' ' \
        --scrollbar autohide \
        -H 25 \
        --fn "Noto Sans Italic 9.7" \
        --tb="#e2e2e2" \
        --tf="#222222" \
        --fb="#e2e2e2" \
        --ff="#222222" \
        --nb="#e2e2e2" \
        --nf="#222222" \
        --hb="#e2e2e2" \
        --hf="#222222" \
        --sb="#e2e2e2" \
        --sf="#e2e2e2"
```

**Comment by Earnestly** [comment]
See https://github.com/Cloudef/bemenu/issues/82

**Comment by guinanseyebrows** [comment]
@Earnestly are there any runtime options to disable or change the cursor settings?

**Comment by guinanseyebrows** [comment]
Oh, I see in #118 that this is not editable right now.
I guess count this as a request to optionally-disable it at runtime :)
