### ISSUE TITLE
Unknown black spot

### ISSUE THREAD

**Issue by Merith-TK** [Cloudef/bemenu#122]
I am using bemenu in combination with swaywm, 
![rsz_20200522_06h42m20s_grim](https://user-images.githubusercontent.com/10422110/82674229-d4f0ce00-9bf7-11ea-8dfc-19a14eabcc06.png)
this is supposed to say `sshcode developer@192.168.0.115` but the black spot covered up the exact same spot every time, 

i am running bemenu with this config `bindsym $mod+d exec bemenu-run`

**Comment by Cloudef** [comment]
This was fixed by commit https://github.com/Cloudef/bemenu/commit/d9f4d1bb12bdf809fa5bd3959607beb7cf341a99

I'll make new release once I find time to fix https://github.com/Cloudef/bemenu/issues/117

**Comment by Merith-TK** [comment]
alright
