### ISSUE TITLE
Bemenu fails to launch certain apps in Sway

### ISSUE THREAD

**Issue by quantizzed** [Cloudef/bemenu#125]
Using Sway with Manjaro.

For example, launching Chromium works, but launching Firefox or Telegram-desktop fails.

On the other hand, if I start Bemenu inside a terminal, both Firefox and Telegram-desktop can be successfully launched.

**Comment by Cloudef** [comment]
This sounds like problem with your environment. When you launch bemenu from terminal it inherits environment of your shell. However sway's environment is different and depends on your setup.

**Comment by Cloudef** [comment]
https://github.com/swaywm/sway/issues/3109 prob related

**Comment by quantizzed** [comment]
Thanks for the hint, you turned out to be absolutely right.
