### ISSUE TITLE
Launching apps with arguments

### ISSUE THREAD

**Issue by fuzunspm** [Cloudef/bemenu#129]
I want to launch QCAD like this:

qcad -platform xcb

how do i achieve same terminal command behavior  with bemenu?

**Comment by Cloudef** [comment]
You can just type that and it should work.

**Comment by fuzunspm** [comment]
It doesn’t work like that

**Comment by Cloudef** [comment]
![Screenshot 2020-08-25 at 15 33 45](https://user-images.githubusercontent.com/480330/91133497-72bcd300-e6e8-11ea-937e-73fc1f46eeef.png)
![Screenshot 2020-08-25 at 15 33 50](https://user-images.githubusercontent.com/480330/91133600-7a7c7780-e6e8-11ea-8615-a17166aaef15.png)
Should work just fine
