### ISSUE TITLE
Update VERSION file to 0.5.0

### ISSUE THREAD

**Issue by petercolberg** [Cloudef/bemenu#130]
Thanks for your work on bemenu. :slightly_smiling_face: 

I am [packaging bemenu for Debian](https://salsa.debian.org/swaywm-team/bemenu) and noticed that the `VERSION` file does not match the latest release, 0.5.0.

**Comment by Cloudef** [comment]
The latest release should now fix this, and the CI now checks that the same mistake doesn't happen again.
