### ISSUE TITLE
Document keybindings.

### ISSUE THREAD

**Issue by crocket** [Cloudef/bemenu#133]
Because keybindings are not documented, I have to read the source code to understand each key binding.

**Comment by fancycade** [comment]
Hi, I've started an attempt at compiling a list of keybindings. I could use some help with filling in the blanks though, or any other corrections. For now I have it in csv format, but I will convert to a proper Markdown table format once it is complete.

Key, Binding
Left Arrow, Move cursor left
Right Arrow, Move cursor right
Up Arrow, Move to previous item
Down Arrow, Move to next item
Home, Curses cursor set to 0
End,
Page Up,
Page Down,
Shift + Page Up,
Backspace, Delete character at cursor
Delete,
Delete Left
Delete Right
Word Delete
Tab, Move to next item
Shift + Tab, Select item
Custom 10 \(F10?\),
Esc, Exit bemenu selection
Return, Execute selected item

**Comment by Cloudef** [comment]
You can find more keybindings here, https://github.com/Cloudef/bemenu/blob/master/lib/renderers/x11/x11.c#L52 basically different combos are mapped to "basic keys" that provide the functionality. shift + left/right map to up/down for example, to allow scrolling in the single line mode as well. https://github.com/Cloudef/bemenu/blob/master/lib/menu.c#L655-L802 here are list of what are considered as "basic keys" and what they do (in code).

**Comment by fancycade** [comment]
@Cloudef Thanks for the direction. I've updated my previous comment with what I believe is all the keybindings. Let me know what you think.

**Comment by Cloudef** [comment]
That looks pretty good, note that SHIFT_RETURN (insert too) is for returning the filter text rather than the highlighted item, or just returning the selected items / if you did multi selection.
