### ISSUE TITLE
bemenu appears behind Waybar and is not visible

### ISSUE THREAD

**Issue by Soundtoxin** [Cloudef/bemenu#134]
I'm using Waybar as my panel on Sway, and it seems bemenu appears behind the bar now. I can't see it (except for a very thin line and color/movement if I type). For now as a work-around I've been passing the -b argument since there's no panel at the bottom of my screen that would block bemenu, but I'd prefer it at the top.

bemenu v0.4.1
sway version 1.4
Waybar v0.9.3

**Comment by Cloudef** [comment]
Did you try the -n argument?

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/issues/81#issuecomment-606062068 this issue may also be related. If panel and bemenu occupy the same layer, the order how they are drawn is undefined.

**Comment by Soundtoxin** [comment]
I didn't know about the -n argument, that seems to work well! It moves it a bit lower than it'd be normally, but at least then I don't have to look down.
If you think it's similar enough to that other issue, I'll leave it up to you to close or not. Thanks for the tip, I had only briefly skimmed the man page and this was my first time using bemenu in a few months.

**Comment by Cloudef** [comment]
Yeah, the -n only avoides overlapping with other panels. Having the bemenu appear on top of the othe panels is related to #81
