### ISSUE TITLE
bemenu not working on alpine linux

### ISSUE THREAD

**Issue by em-dash** [Cloudef/bemenu#139]
I'm not able to use bemenu or bemenu-run on alpine linux. 

Under Wayland in hikari (have had this working together with bemenu on Arch), it exits immediately, and `echo $?` returns `1`. With sway it doesn't exit, but doesn't start the interface either. 

In a tty, it keeps running but doesn't produce any output.

**Comment by fancycade** [comment]
@em-dash Could you go into more detail about how are you installing it?

I'm currently using bemenu with Wayland on Alpine. 

It sort of sounds like it might be trying to use Xorg instead of wayland.

I've been building it from source like so:

```
make clients wayland
```

**Comment by em-dash** [comment]
I've tried installing it through both the official repos, and building it with aports. I also tried just now installing it from just the git repo using `make clients wayland`, and I'm still having the same issue. 

I'll have a go with a fresh alpine to check if I've messed anything up. What compositor are you running that it's working with?

**Comment by fancycade** [comment]
For Wayland, I wouldn't use the Alpine packages as they won't be up to date. There have been some minor fixes recently, but not a release from bemenu as there is still some ongoing work.

Just to be clear `make clients wayland` only does the build, you have to run `sudo make install` to actually install it.

I'm using Sway.

**Comment by em-dash** [comment]
Ah thank you! It seems like the problem must have been that I was running `sudo make install PREFIX=/usr` when installing (without the package manager). `sudo make install` without setting a prefix has worked and it now works as expected.

**Comment by Cloudef** [comment]
It would work with PREFIX if you also used the PREFIX during build as well. From the readme:
>Other usual variables are available for modifying such as DESTDIR, bindir, libdir and mandir
>Note that if you want a custom PREFIX or libdir, you should pass those during build as well,
>since they will be used compile-time to figure out where to load backends from!

It's also possible to run bemenu without installing like this:
>To test from source, you have to point the LD_LIBRARY_PATH and BEMENU_RENDERERS variables:
>`LD_LIBRARY_PATH=. BEMENU_RENDERERS=. ./bemenu-run`

However note that installing anything into /usr without package manager is usually a bad idea.
