### ISSUE TITLE
selecting multiple inputs

### ISSUE THREAD

**Issue by holomorph** [Cloudef/bemenu#14]
There are two discrepancies between bemenu and dmenu. When selecting multiple entries with `C-RET`,
1.  in dmenu, you print the selection with `S-RET`, whereas in bemenu `S-RET` is the same as `ESC`. Additionally, `C-[` doesn't behave as `ESC`.
2. in bemenu, hitting `RET` will print both the selected entries and and the highlighted entry whether or not the highlighted entry was selected.  dmenu will only launch selected entries with `S-RET`, and only the highlighted entry with `RET` whether or not there are selected entries.

The former amounts to trivial changes, but consistency would be nice.  The latter I find to be unexpected, being a dmenu user.  I like that in dmenu, even if I were to select a bunch of entries, I still have the choice to launch only the one highlighted entry, or all the selected ones.

**Comment by Earnestly** [comment]
I never really liked dmenu's method of multiple selection personally, it feels clunky and awkward.

I think that `RET` working in bemenu as it does now is much more intuitive than dmenu's `S-RET` because it is more often in my case that the last item I highlight is the last item I want to include, having to highlight this becomes tedious ceremony.

That said `S-RET` should be a no-op or made to behave like `RET` to avoid unexpected behaviour imo.

**Comment by Cloudef** [comment]
S+Ret in bemenu is actually same as insert, it prints the filter line.

**Comment by holomorph** [comment]
I guess this `case S-RET:` shouldn't be there, then
``` c
        case BM_KEY_SHIFT_RETURN:
        case BM_KEY_ESCAPE:
            list_free_list(&menu->selection);
            break;
```

**Comment by Cloudef** [comment]
That case is bit misleading. bemenu.c client has some additional logic.
I should change that case to actually create item and select it instead of doing it like this.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/bc584cc5f033518517b5f60c815815b5b57c8c81
The S-Ret is now more elegant in the code. I'm not gonna make multiple selections to work like in dmenu as I agree with @Earnestly that in bemenu it feels better. If that is something that people need though, open a new issue for that issue. `C-[` should have been working as well for quite a while now.
