### ISSUE TITLE
Add parameter for pre-selection of entries.

### ISSUE THREAD

**Issue by jmehne** [Cloudef/bemenu#140]
Hi,

first off: thank you so much for bemenu, I really enjoy using it. I was wondering if it is possible to pre-fill the input prompt to provide a default subset of entries (I didn't find a solution in the docs), or if you would consider (taking patches for) such a feature?

Rationale: I use bemenu in combination with the [pass](https://www.passwordstore.org/) password manager.
I would like to offer all entries that match a certain string as a pre-selection.
E.g., the following command:
```
bemenu --pre-selection "reddit.com"
"reddit.com/foobar"
"reddit.com/bar"
"gmail.com/foobar"
```
would pre-fill the input prompt with `reddit.com` and thus only show `reddit.com/foobar` and `reddit.com/bar`.
But the user could just delete everything and still choose from the whole set of all available entries.

**Comment by Cloudef** [comment]
Sounds like a good feature for me. `--pre-selection` may be a misleading name. Could be named `--filter` perhaps, that's how bemenu internally refers to the string user types. Another common name used for this kind of feature would be "placeholder".

**Comment by jmehne** [comment]
Great, I'll give it a try.
