### ISSUE TITLE
bemenu --grab, -f appears to no longer work

### ISSUE THREAD

**Issue by Earnestly** [Cloudef/bemenu#142]
When using `bemenu -f` it appears to block on "Loading..." indefinitely:

```sh
$ printf '%s\n' item | bemenu -f -l 30
```

A simple `gdb` run of bemenu (without many symbols, so perhaps not useful) shows the backtrace containing:

```
#0  0x00007ffff7e94437 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff734f63b in  () at /usr/lib/libxcb.so.1
#2  0x00007ffff735137b in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007ffff7b983e9 in _XReadEvents () at /usr/lib/libX11.so.6
#4  0x00007ffff7b86ec9 in XNextEvent () at /usr/lib/libX11.so.6
#5  0x00007ffff7fc221c in  () at /usr/lib/bemenu/bemenu-renderer-x11.so
#6  0x0000555555556fd1 in  ()
#7  0x0000555555556076 in  ()
#8  0x00007ffff7dc7152 in __libc_start_main () at /usr/lib/libc.so.6
#9  0x000055555555623e in  ()
```

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/8c93e0081b8864ca0baff8d80022bd60affceeb6 its currently disabled for reason as it may lock your session.

**Comment by Earnestly** [comment]
Strange, I've been using it for the last week yet this commit appears to be from 2017

**Comment by Cloudef** [comment]
Hmm. That sounds strange indeed. I'll see if I can reproduce later.

**Comment by Earnestly** [comment]
I'm not sure if it was a change in Xorg but this appears to be working again.  I do quite like how it doesn't immediately grab the input but instead displays bemenu as loading.  This is a nice way to know something is coming for slow (e.g. curl) producers.

**Comment by joanbm** [comment]
@simoneruffini Yours is actually a new issue and is most likely going to be fixed by https://github.com/Cloudef/bemenu/pull/273.
