### ISSUE TITLE
setting font inside bash script doesn't work

### ISSUE THREAD

**Issue by flipflop133** [Cloudef/bemenu#147]
I wrote the following code inside a bash script and I noticed that the font size wasn't take into account.
`font="'RobotoMono 25'"`
`menu="bemenu --fn $font"`

**Comment by Earnestly** [comment]
http://mywiki.wooledge.org/Quotes

**Comment by flipflop133** [comment]
Actually I tried all bash ways I was aware of and that are described in your link and I'm still unable to change the font size, maybe I'm missing something tough.
Trying the following doesn't work for example:
`menu="bemenu-run --fn \"RobotoMono 25\""`
`$(echo test | $menu)`
Script link:
https://github.com/flipflop133/Dotfiles/blob/master/.config/sway/dmenupower.sh

**Comment by flipflop133** [comment]
Also noticed that the first element gets printed reversed (maybe it's issues on my side but all this script was working fine with dmenu)
![image](https://user-images.githubusercontent.com/48946818/104653703-4ddaf380-56bb-11eb-8e56-0a65cc8800a8.png)

**Comment by Earnestly** [comment]
Please read the bash guide on the wooledge website when you have a chance.  I only fixed all scripting the errors:

```sh
#!/bin/bash

# icons
icon_path=/usr/share/icons/Papirus/48x48/apps
shutdown=system-shutdown.svg
reboot=system-reboot.svg
log_out=system-log-out.svg
suspend=system-suspend.svg
suspend_hibernate=system-suspend-hibernate.svg
screen=cs-screen.svg

# menu
font='RobotoMono 25'
menu() { bemenu-run --fn "$font"; }
logoff_cmd() { sway exit; }

select=$(printf ' Poweroff\nﰇ Reboot\n﫼 Logout\n鈴 Suspend\n Hibernate\n PowerMode\n祥 Screen timeout' | menu)

case $select in
	" Poweroff")
		notify-send -i "$icon_path/$shutdown" "Shutting down..."
		sleep 1
		poweroff
		;;
	"ﰇ Reboot")
		notify-send -i "$icon_path/$reboot" "Rebooting..."
		sleep 1
		reboot
		;;
	"﫼 Logout")
		notify-send -i "$icon_path/$log_out" "Logging off..."
		sleep 1
		logoff_cmd
		;;
	"鈴 Suspend")
		notify-send -i "$icon_path/$suspend" "Suspending..."
		sleep 1
		systemctl suspend
		;;
	" Hibernate")
		notify-send -i "$icon_path/$suspend_hibernate" "Hibernating..."
		sleep 1
		systemctl hibernate
		;;
	" PowerMode")
		kitty -e sudo "$HOME"/.config/scripts/bash/Tools/powersave.sh
		;;
	"祥 Screen timeout")
		timeout=$(printf "鈴 Enable screen timeout\n零 Disable screen timeout" | menu)
		;;
esac

case $timeout in
	"鈴 Enable screen timeout")
		"$HOME"/.config/scripts/bash/Tools/idle.sh
		notify-send -i "$icon_path/$screen" "Screen timeout enabled"
		;;
	"零 Disable screen timeout")
		if "$HOME"/.config/scripts/bash/Tools/idle.sh 0;then
			notify-send -i "$icon_path/$screen" "Screen timeout disabled"
		fi
		;;
esac
```

Consider also using `shellcheck` too.

**Comment by flipflop133** [comment]
Thanks a lot to take the time to answer me and explain everything, I got everything fixed and all is working like a charm!
I learned a lot, thanks to you, going to read more on bash!
PS: I was already using shellcheck, it's a great tool.
