### ISSUE TITLE
using a custom list of programs

### ISSUE THREAD

**Issue by ghost** [Cloudef/bemenu#149]
i don't want bemenu to list all programs in /bin
so i was thinking if its possible to make a list of programs and bemenu reading from it

**Comment by Earnestly** [comment]
Set a custom `PATH` environment for it:

```sh
PATH=/custom command -p bemenu-run
# Or
PATH=/custom /bin/bemenu-run
```

**Comment by DaniV5** [comment]
so i need to make a symbolic link for the programs i want right?

**Comment by Earnestly** [comment]
Please read the manual for `bemenu`.  `bemenu-run` specifically exists to process `PATH` items.

**Comment by DaniV5** [comment]
ok i've read the manual, but didn't find anything for this problem and PATH=/custom didn't work
i got "bash: bemenu-run: command not found"

**Comment by Earnestly** [comment]
Unreal.

**Comment by DaniV5** [comment]
heh... i forgot one part
it works now

**Comment by DaniV5** [comment]
ok not good
if i run a terminal with this PATH command the terminal will also use the PATH
and not read from /bin
same with a file mannager, if i open a file manager and in the file manager i open a terminal it will be reading from the custom PATH

**Comment by Cloudef** [comment]
You could use bemenu-run with the `--no-exec` flag and do something like this:
`"$(PATH=mypath /usr/bin/bemenu-run --no-exec)"`
Alternatively you can make your own launcher with `bemenu` instead of `bemenu-run` which would give you more flexibility.
