### ISSUE TITLE
Colors for the command line don't work on Sway.

### ISSUE THREAD

**Issue by LiterallyJohnny** [Cloudef/bemenu#151]
I am trying to change the colors for bemenu (Namely the background color and the text) and it appears that none of the command line arguments are working.

I saw that there was already a post about this, but it doesn't seem to help my issue. Below is the command I am trying to run:

*This is the command I am using in my Sway config. I have another command that executes `$menu.`*
```
set $menu bemenu-run --no-overlap --ignorecase --prompt="Exec:" --fn "Open Sans 10" --nb=2a2b2a
```

It doesn't seem to do anything. 

Also, the documentation on all of the available options are not very descriptive at all. I mean, what's the difference between "normal foreground" and "normal background"?

For a simple application launcher, why are there *12* color options?

Nevermind that, could someone help me understand why the colors aren't working?

**Comment by Earnestly** [comment]
`--nb='#2a2b2a'` (`#RRGGBBAA`)

**Comment by LiterallyJohnny** [comment]
Well don't I feel dumb now.

Thanks for this, lol. You have a good one bud.
