### ISSUE TITLE
WAYLAND_DISPLAY is not taken into account

### ISSUE THREAD

**Issue by piater** [Cloudef/bemenu#153]
`wayland.c` calls `wl_display_connect(NULL)`, apparently assuming that this will cause the callee to consult the WAYLAND_DISPLAY environment variable. However, it does not; it defaults to `wayland-0`. Thus, the call should be `wl_display_connect(getenv("WAYLAND_DISPLAY"))`.

I discovered this when running the git version of sway which sets `WAYLAND_DISPLAY=wayland-1`, which causes bemenu to quit immediately without diagnostics.

**Comment by Cloudef** [comment]
hmm NULL should work
see:
https://manpages.debian.org/experimental/libwayland-doc/wl_display_connect.3.en.html
https://github.com/wayland-project/wayland/blob/1ab6a81816f52c17be2138ba569256b5afc029f2/src/wayland-client.c#L967

**Comment by Cloudef** [comment]
The WAYLAND_SOCKET variable may be conflicting with the WAYLAND_DISPLAY 
https://github.com/wayland-project/wayland/blob/1ab6a81816f52c17be2138ba569256b5afc029f2/src/wayland-client.c#L1141

The WAYLAND_SOCKET Is most likely set by wlroots/sway.

**Comment by piater** [comment]
I have been unable to reproduce the issue; perhaps it was due to system inconsistencies between sway crash and upgrade. Sorry for the noise.
