### ISSUE TITLE
Can't execute bemeu

### ISSUE THREAD

**Issue by Fabioah** [Cloudef/bemenu#155]
Hi, when i try to launch bemenu or bemenu-run I always get this error

`bemenu: symbol lookup error: bemenu: undefined symbol: bm_menu_set_monitor_name`
or
`bemenu-run: symbol lookup error: bemenu-run: undefined symbol: bm_menu_set_monitor_name`

I am currently using archlinux with Wayland and I tried both aur and github version with same results.

**Comment by Cloudef** [comment]
It sounds like your executables and libbemenu are out of sync. Make sure you have the up-to-date libbemenu in your library path.

**Comment by Fabioah** [comment]
Yes I had bin files from github installation and the remaining from aur one. Thank you.
