### ISSUE TITLE
Introduce alternative keybinds

### ISSUE THREAD

**Issue by dboso** [Cloudef/bemenu#156]
Hi

I would like to be able to use alternative keybindings for navigating the menu
'Move to previous item' - Ctrl-k
'Move to next item' - Ctrl-j
'Exit bemenu' - Ctrl-c

I see that there already exist bindings for these actions, namely
'Move to previous item' - Up Arrow
'Move to next item' - Down Arrow

Moreover I also notice that we have the bindings
'Select next item' - Ctrl + n
'Select previous item' - Ctrl + p

What's the difference between e.g. Up Arrow and Ctrl + p?

What would be the prefered way to introduce my preferred keybinds in bemenu?
- Hardcode the key bindings
- Introduce a configuration that allows the user to overwrite existing key bindings
- Something else?

Regards

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/issues/108 there's some discussion about this here and here https://github.com/Cloudef/bemenu/issues/104
The codebase would need quite bit of refactoring for custom keybindings. It's encouraged to patch the backends instead for your personal modifications.

**Comment by dboso** [comment]
I see
Somehow i missed #108
I will close this one
