### ISSUE TITLE
Feature Request: Config Files/default Flags

### ISSUE THREAD

**Issue by user18130814200115-2** [Cloudef/bemenu#158]
A simple config file to set the same options usually passed as flags to bemenu such as colours and fonts would be nice.
Currently the defaults are defined in lib/menu.c.

**Comment by Cloudef** [comment]
It's possible to configure bemenu with env variable `BEMENU_OPTS`

**Comment by user18130814200115-2** [comment]
I don't know how I completely missed this feature, Thank you!

**Comment by Soundtoxin** [comment]
@Cloudef Can you give me a usage example of the BEMENU_OPTS thing? Like, setting the font and no-overlap for example. I didn't see one in the manual, there's no wiki entries for this repo, and my first few attempts have not worked.

**Comment by user18130814200115-2** [comment]
You literaly make a command the way you like, EG:
```
bemenu -i --fn monospace
```
And replace `bemenu` with `export BEMENU_OPTS=`

The difficulty comes with quoted strings for things like colours, you will need to remove all quotation marks form your opts.

As an example, here is  my `BEMENU_OPTS` variable:
```
export BEMENU_OPTS="-i --fn monospace --tb #334d67 --tf #81a1c1 --fb #D8DEE9 --ff #2E3440 --nb #D8DEE9 --nf #2E3440 --hb #81a1c1 --hf #D8DEE9 -H 27 -p '' -f"
``
