### ISSUE TITLE
Behaviour of -m is incompatible with dmenu

### ISSUE THREAD

**Issue by nmeum** [Cloudef/bemenu#164]
While switching my dwm setup from dmenu to bemenu, I noticed that bemenu's current `-m` behaviour is incompatible with dmenu's original `-m` behaviour. With dmenu, monitor indices start at 0 and a value of -1 (the default) is used to spawn dmenu on the current monitor. With bemenu, monitor indices start 1 and a value of 0 (the default) is used to spawn on the current monitor. Would you be interested in align the default -m behaviour with the dmenu behaviour? I only tested this with the x11 backend, not with the wayland backend.

**Comment by Cloudef** [comment]
Since the aim is to be compatible, I think we should follow dmenu's syntax.
