### ISSUE TITLE
pinentry

### ISSUE THREAD

**Issue by t-8ch** [Cloudef/bemenu#168]
I have written a [pinentry](https://www.gnupg.org/related_software/pinentry/index.en.html) tool based on bemenu, that can be used by gpg-agent and similar software to unlock SSH and GPG keys:

https://github.com/t-8ch/pinentry-bemenu

This issue is meant to be found by people searching bemenus ticket tracker for such a tool.
Feel free to delete the ticket if this is too much advertisement.

FYI for this tool it would be nice to have the `bm_menu_set_password()` functionality be available in a released version.

**Comment by Cloudef** [comment]
Feel free to also make PR for "Project using bemenu" section for the README.md

**Comment by t-8ch** [comment]
Sorry for bumping this again.

For `pinentry-bemenu` it would be very nice to have `bm_menu_set_password()` available in a released version of bemenu.
According to #105 it seems to be reasonable to request a release :-)

**Comment by Cloudef** [comment]
I'll make github action to automate release packages

**Comment by t-8ch** [comment]
Thanks a lot!

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/releases/tag/0.6.0 included here now, the releases are now automated.

**Comment by t-8ch** [comment]
Thanks again!
