### ISSUE TITLE
'cairo/cairo.h' file not found

### ISSUE THREAD

**Issue by concatime** [Cloudef/bemenu#170]
When building bemenu (and sway too), I face this:
```
In file included from lib/renderers/wayland/wayland.c:2:
In file included from lib/renderers/wayland/wayland.h:9:
lib/renderers/cairo.h:8:10: fatal error: 'cairo/cairo.h' file not found
#include <cairo/cairo.h>
         ^~~~~~~~~~~~~~~
1 error generated.
In file included from lib/renderers/wayland/registry.c:1:
In file included from lib/renderers/wayland/wayland.h:9:
lib/renderers/cairo.h:8:10: fatal error: 'cairo/cairo.h' file not found
#include <cairo/cairo.h>
         ^~~~~~~~~~~~~~~
1 error generated.
In file included from lib/renderers/wayland/window.c:2:
In file included from lib/renderers/wayland/wayland.h:9:
lib/renderers/cairo.h:8:10: fatal error: 'cairo/cairo.h' file not found
#include <cairo/cairo.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

This issue happens because pkgconfig strips the cairo namespace.
Relevant part from`/lib/pkgconfig/cairo.pc`:
```
Cflags: -I${includedir}/cairo
```
You can verify by yourself from [Archlinux’s package](https://archlinux.org/packages/extra/x86_64/cairo/download/).

I don’t know if this behaviour is for keeping backward compatibility, or that cairo namespace is deprecated.

Two options:
1. Rename `lib/renderers/cairo.h` to `lib/renderers/cairo_internal.h`, and replace `<cairo/cairo.h>` by `<cairo.h>` from it, otherwise we would have two `cairo.h` in compiler’s search path and probably an issue.
2. Remove stripping from upstream cairo.

**Comment by concatime** [comment]
Should I open an issue in sway too? This way we can opt for a common solution.

**Comment by Cloudef** [comment]
I guess we should rename cairo.h to cairo_renderer.h or something and then use cairo.h, pretty weird the pc file has changed like that.

**Comment by concatime** [comment]
I faced this issue with swaybg too, so I’ve opened an issue upstream https://gitlab.freedesktop.org/cairo/cairo/-/issues/479 once for all. We will wait for their response before any action.

**Comment by psychon** [comment]
> You can verify by yourself from Archlinux’s package.

Does anyone know what exactly causes this? I downloaded the Archlinux package and it installs `cairo.h` to `/usr/include/cairo/cairo.h`, so shouldn't `#include <cairo/cairo.h>` still work?

**Comment by Cloudef** [comment]
![Screenshot 2021-05-07 at 23 31 07](https://user-images.githubusercontent.com/480330/117465119-51f19080-af8c-11eb-927f-d2be096e7e95.png)
Seems like it was answered. While unfortunate, we aren't doing the cairo include the documented way so we should fix it. Most likely bemenu won't be the only project where this issue happens.

**Comment by Cloudef** [comment]
maybe fixed here https://github.com/Cloudef/bemenu/commit/ebd7338bd5653a56d319a3a879f97e867413e58b

**Comment by concatime** [comment]
@psychon Well, I didn’t install cairo to `/usr`, and expected, rightfully, that `pkg-config --cflags cairo` would be enough (which wasn’t)

**Comment by concatime** [comment]
I confirm it works. Thank you.

**Comment by Cloudef** [comment]
Thanks, I'll try to prepare new release soon including this fix.
