### ISSUE TITLE
curses backend inserts Ě into the prompt whenever I change font size in alacritty.

### ISSUE THREAD

**Issue by crocket** [Cloudef/bemenu#176]
`Ctrl - =` increases font size in alacritty.
`Ctrl - -` decreases font size in alacritty.

Whenever I change font size in alacritty, curses backend inserts Ě into the prompt as below.

![2021-06-06 13:55:30](https://user-images.githubusercontent.com/748856/120913029-fde2e480-c6ce-11eb-9244-b4ff2516a2ba.png)

bemenu-0.5.0 didn't have this problem.

**Comment by crocket** [comment]
I guess there is a problem with curses backend or alacritty's terminfo file.

**Comment by crocket** [comment]
It also distorts characters inserted by CJK input methods.

![2021-06-06 20:05:46](https://user-images.githubusercontent.com/748856/120922207-bb3aff80-c702-11eb-832f-20cac5d7c07d.png)
![2021-06-06 20:05:49](https://user-images.githubusercontent.com/748856/120922209-c1c97700-c702-11eb-8d3d-9e49b435d62e.png)

**Comment by Cloudef** [comment]
I tracked the issue to this PR:
https://github.com/Cloudef/bemenu/pull/127
and reverted the curses side changes in this commit:
https://github.com/Cloudef/bemenu/commit/ca6b9034150bb0886c31b4e9ad934db9ec8fd2e2

As a side note, at some point I think the curses will be get rid completely for custom vt100 based solution https://github.com/Cloudef/bemenu/issues/50 this should allow better key handling and more unifying look with the other backends.

**Comment by crocket** [comment]
I tested the latest commit. The issue is fixed.
