### ISSUE TITLE
Allow control-c to dimiss?

### ISSUE THREAD

**Issue by tmpm697** [Cloudef/bemenu#182]
like `dmenu` that allow press control-c to dismiss/quit bemenu. I find it convenient way exit.

**Comment by tmpm697** [comment]
any hint on this? I really want this feature. @Cloudef

**Comment by Cloudef** [comment]
Fastest way to have this in is to send a PR.
Should be pretty straightforward to add here:
https://github.com/Cloudef/bemenu/blob/master/lib/renderers/x11/x11.c#L52-L185
and here:
https://github.com/Cloudef/bemenu/blob/master/lib/renderers/wayland/wayland.c#L80-L206

**Comment by tmpm697** [comment]
@Cloudef thanks. PR in https://github.com/Cloudef/bemenu/pull/192
