### ISSUE TITLE
Respect keyboard rate in sway?

### ISSUE THREAD

**Issue by tmpm697** [Cloudef/bemenu#183]
I'm using sway and I've noticed that keyboard in `bemenu` lag behind normal use of my keyboard rate (that I've set in sway/config). 

Seem like it maintain its own keyboard rate and ignore sway config.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/blob/master/lib/renderers/wayland/registry.c#L418 I think the problem is this line, it overrides the repeat info received from sway. This function call should be done earlier.

**Comment by fancycade** [comment]
Based on some testing, keyboard_handle_repeat_info is never triggered. The sway info was never set in the first place.

Tested on sway with this in my config:

`input type:keyboard {
    repeat_delay 200
    repeat_rate 30
}
`

**Comment by fancycade** [comment]
https://github.com/Cloudef/bemenu/blob/69d030573c9673d75b07d7a493b6c2cf4bf1f06c/lib/renderers/wayland/registry.c#L331

Changing the 1 on this line to a 7 fixes the issue with keyboard_handle_repeat_info never being triggered.

Found this by comparing to wayland-book:
https://git.sr.ht/~sircmpwn/wayland-book/tree/master/item/src/seat/example.md?view-source#L43

**Comment by tmpm697** [comment]
@fancycade : thanks, smooth scroll now.

@Cloudef : can you update the code?
