### ISSUE TITLE
Accept user input?

### ISSUE THREAD

**Issue by tmpm697** [Cloudef/bemenu#184]
I have this work in `dmenu`: 
```
terminal> dmenu -p "Enter pass: " <&-
```
that will display `dmenu` and user can start to type in, chars after type will be echoed to terminal .

I tried with `bemenu` but it does nothing, can you support this? as I find it very useful for accept input from user for password management with `bemenu`.

**Comment by Cloudef** [comment]
I'm not really sure what you mean, if you have problems with stdin, you can pass /dev/null like, `bemenu -p "Enter pass: " < /dev/null`

**Comment by tmpm697** [comment]
Nice, `< /dev/null` makes it work. thanks.
