### ISSUE TITLE
Support for wlroots 0.14.0

### ISSUE THREAD

**Issue by ainola** [Cloudef/bemenu#186]
Hello, and thanks for this great project!

wlroots 0.14.0 was [released](https://github.com/swaywm/wlroots/releases/tag/0.14.0) a few days ago which does feature a few breaking changes. Indeed, it appears that bemenu segfaults out of the gate when running the binary:

```
Stack trace of thread 1597174:
#0  0x00007fe6e94e2a0e __strcmp_avx2 (libc.so.6 + 0x15ba0e)
#1  0x00007fe6e9556795 n/a (libbemenu.so.0 + 0x3795)
#2  0x00007fe6e95568d1 n/a (libbemenu.so.0 + 0x38d1)
#3  0x00007fe6e9556ad4 bm_init (libbemenu.so.0 + 0x3ad4)
#4  0x00005647b62433a7 n/a (/path/to/bemenu-0.6.2/bemenu + 0x23a7)
```

**Comment by Cloudef** [comment]
Can you get another backtrace with bemenu compiled with debug symbols?

**Comment by ainola** [comment]
I'm sorry, this was entirely my environment's fault. I'm sorry to bother you.
