### ISSUE TITLE
Priority candidate in condition?

### ISSUE THREAD

**Issue by tmpm697** [Cloudef/bemenu#187]
In case that I have many candidate but I switch/select often between two, so:
```
bemenu if smth, put "abc" on top candidate, else put "def" on top candidate
```
Can `bemenu` do this? or would like to support?

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/issues/180 maybe related?

**Comment by tmpm697** [comment]
Not quite sure, but doing two bemenu wouldn't hurt I suppose, but it's nice to have native support.

I'll let this open if someone has interest. Thanks.

**Comment by tmpm697** [comment]
But actually I still need to pin a candidate at least, howto?

**Comment by tmpm697** [comment]
Or how can I keep order of list when I pipe to bemenu: `echo "yes\nno" | bemenu` will put `yes` and `no` in order list of candidate.

But `echo "no\nyes" | bemenu` will put `no` and `yes` instead.

**Comment by Cloudef** [comment]
I'm not sure what you are asking. If the order of items in the input is problem you can preprocess it yourself.
For example `echo -n "yes\nno" | sort | bemenu`
