### ISSUE TITLE
Draw borders?

### ISSUE THREAD

**Issue by Barbaross93** [Cloudef/bemenu#193]
I was wondering if there were plans to be able to draw borders around the bemenu window? If not, where in the code should I look if I wanted to send a PR?

**Comment by Cloudef** [comment]
All the drawing stuff for x11 and wayland is in this file: https://github.com/Cloudef/bemenu/blob/master/lib/renderers/cairo_renderer.h

**Comment by Barbarossa93** [comment]
Shoot, this might be a bit more than I can handle :(

Is there always a one pixel border drawn? If I can find the appropriate line(s) that does this, it may be as simple as adding a border width to it.

**Comment by Cloudef** [comment]
> Is there always a one pixel border drawn? If I can find the appropriate line(s) that does this, it may be as simple as adding a border width to it.

Do you mean something like x11 window border? Wayland doesn't have such concept, so it would be more portable if you did the border drawing in the cairo_renderer.h

**Comment by Barbarossa93** [comment]
No, I meant through cairo. It might just be that my line height isn't as high as it should be, but it seemed like there was a one pixel border. It's noticeable if you have a background color set for one element such as the prompt string compared to the default background.

If I'm going to do a PR, I definitely want to do it right and do it through cairo.

If I'm reading the `cairo_renderer` code correctly, it looks like the `bm_cairo_draw_line` function is the one I want to mess with? or do I want to play with `paint.box`/`paint.pos`?

**Comment by Cloudef** [comment]
I think you want to use the cairo functions directly instead, the bm_cairo functions mainly work with text. Line here meaning a line of text.

**Comment by Barbarossa93** [comment]
Nevermind, regarding colors, I think I figured that out :) Unfortunately things do get covered up if the border is too thick, so still not sure how to deal with this.
