### ISSUE TITLE
bemenu freezes window manager when kept open for too long

### ISSUE THREAD

**Issue by CyborgSquirrel** [Cloudef/bemenu#195]
When I keep bemenu open for about 10 seconds, my window manager (dwl) freezes: the screen stops refreshing and the shortcut for stopping the wm doesn't work. Here's a video of it happening: https://user-images.githubusercontent.com/13777584/128034272-1143d85e-52fc-40a9-8f5b-ce2d243c12e3.mp4

In the video I'm scrolling through the options, but even if I don't do anything my wm freezes.

In case it's important, I'm running artix linux with runit.

**Comment by Cloudef** [comment]
Can you reproduce this issue on another wm, or even wayland? Can you switch to another tty when it's frozen?

**Comment by CyborgSquirrel** [comment]
I can’t switch to another tty, but I haven’t tried using another wm. I’ll
try later today and write back.

**Comment by Cloudef** [comment]
If you can't switch to another tty, it sounds like the whole system is locked up or you don't have tty switching keys enabled.

**Comment by CyborgSquirrel** [comment]
I can switch to another tty when it isn't frozen, so my tty switching keys should be enabled.

Also, I can restart my wm through a hotkey if I have a hotkey daemon running, so I think that means that the whole system isn't locked up.

**Comment by Cloudef** [comment]
All right, sounds like you might be hitting infinite loop somewhere then.

**Comment by CyborgSquirrel** [comment]
I tried doing the same thing in sway and it doesn't freeze, so this is most likely specific to dwl. I'll see if I can try it on some more wms.

**Comment by CyborgSquirrel** [comment]
When I run it with curses backend it also doesn't freeze.

**Comment by CyborgSquirrel** [comment]
I've found out that this is actually an issue with dwl, which can be fixed by merging this pull request https://github.com/djpohly/dwl/pull/130 . Sorry for pinning it on bemenu.
