### ISSUE TITLE
[Feature Request] Match counter and page counter

### ISSUE THREAD

**Issue by rieje** [Cloudef/bemenu#204]
Match counter, e.g. `7/95` for 7 current matching results out of 95 total. This can be displayed at the end of the line. Like [this](https://youtu.be/WAbkzPGhYFI?t=127)

Also, a counter for current pages out of total is IMO cleaner than a scrollbar. Usually a scrollbar implies the use of mouse but dmenu is keyboard-driven.

**Comment by dynamicdotvoid** [comment]
I've gotten working on it, I'll make a PR soon. Would you prefer simply "x/y" or "[x/y]"? With the first option it's somewhat hard to quickly see if there are application names next to it depending on your configuration.

**Comment by dynamicdotvoid** [comment]
Or, I could try and add some margin in between the counter and the application names.

**Comment by rieje** [comment]
Probably a small margin looks a little more cohesive with the rest of the menu but either is fine. Personally I use vertical menus only. Thanks!
