### ISSUE TITLE
Blurry font on multiple monitor with different scaling on Wayland

### ISSUE THREAD

**Issue by minhduc0711** [Cloudef/bemenu#208]
The text are blurry on only one monitor in my setup:
* Monitor 1, scale = 1.41 -> blurry
* Monitor 2, scale = 1.00 -> not blurry

When I remove monitor 2, the text becomes non-blurry on monitor 1.

I'm using sway on Wayland.

**Comment by Cloudef** [comment]
It sounds like for some reason scale 1.00 is used on both monitors. What happens if you force scale with BEMENU_SCALE env variable?

**Comment by minhduc0711** [comment]
I tried `BEMENU_SCALE=1.41` but bemenu remains blurry. It seems like other fractional values such as 1.5, 1.6,... have no effect either, and but the menu text does become bigger when I use integer values such as 2 or 3.

**Comment by Cloudef** [comment]
Wayland doesn't actually support fractional values, the value has to be integer. BEMENU_SCALE could do it, but currently it simply overrides the value read from wl_output. Compositors that do "fractional scaling" simply request buffer with nearest or larger integer scale and then scale down / up.
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/47

**Comment by minhduc0711** [comment]
I see, thank you for the explanation. However, I haven't seen this behavior in other native Wayland apps yet, so I think sway is not probably at fault.

**Comment by Cloudef** [comment]
If you know how to compile the bemenu yourself, can you add 
`printf("%s -> %d:%d\n", output->name, window->scale, output->scale);` to https://github.com/Cloudef/bemenu/blob/master/lib/renderers/wayland/wayland.c#L332 , run the bemenu from terminal and see what it says. Alternatively terminal output of running bemenu with `WAYLAND_DEBUG=1` set may be enough as well.

**Comment by minhduc0711** [comment]
As you prediceted, the output stays unchanged regardless of which monitor I'm using, making scale = 1 on both monitors.
```
HDMI-A-1 -> 1:1
```

**Comment by Cloudef** [comment]
That's weird. Can I have `WAYLAND_DEBUG=1` output as well.

**Comment by minhduc0711** [comment]
* When `HDMI-A-1` is connected: [wl_debug_blurry.log](https://github.com/Cloudef/bemenu/files/7501996/wl_debug_blurry.log)
* When it's disconnected: [wl_debug_correct.log](https://github.com/Cloudef/bemenu/files/7502001/wl_debug_correct.log)

**Comment by Cloudef** [comment]
>Just to clarify more on the issue, the text becomes blurry when I focus the eDP-1 output and launch bemenu. When I specify that same output with the -m flag, then the text would be perfectly crisp.

This explains it. Bemenu uses the `wlr-layer-shell` protocol to place bemenu surface on wayland. Bemenu actually has no idea which monitor is the "focused" one, but compositor decides this, and this is where the oversight is. The fix here is for bemenu to implement wl_surface's enter/exit events and use those to determine which monitor window landed on.
