### ISSUE TITLE
Is it possible to add command-line arguments to launched programs?

### ISSUE THREAD

**Issue by pjhades** [Cloudef/bemenu#212]
Hi! I would like to know if it's possible to configure bemenu to add arguments to a launched program, so that I could for example run chromium as `chromium --foo --bar`.

Thanks!

**Comment by Earnestly** [comment]
No but you can also type those arguments directly.  You can also create local wrappers which apply the arguments and conditions as you wish.  It's not really something bemenu should know about or do.

**Comment by pjhades** [comment]
Thanks!
