### ISSUE TITLE
New options added in bemenu 0.6.4 are not documented in the man page

### ISSUE THREAD

**Issue by nmeum** [Cloudef/bemenu#216]
It seems like the following options have been added to `bemenu(1)` with the 0.6.4 release:

* `-c`: a42fa97a49c4bb2ec20111b439179992a0e31f34
* `--ch`: 0589962d1cc06e9bb63b5ef25aa812d6eba4a3d4
* `-s`: 9b2a2cabf2f9865a6a9f278c09187bdf0ab6e8af
* `-M`: bddeea05b6de09ec1c48e6bef2b05428e442b982

Unfortunately, these options are not documented in the provided man page. IMHO it would be nice to align the output of `--help` with the man page or maybe just have `--help` open the man page like `git(1)` does for example to avoid such inconsistencies in the future.

**Comment by quite** [comment]
All these options *are* at least documented in the current 0.6.23 release. This can be closed.
