### ISSUE TITLE
Error while loading libbemenu.so.0

### ISSUE THREAD

**Issue by noiseredux2** [Cloudef/bemenu#217]
bemenu says this error while trying to launch:

`bemenu: error while loading shared libraries: libbemenu.so.0: cannot open shared object file: No such file or directory`

Installed all the dependencies for Debian before make and using sway with xwayland disabled.

**Comment by lokesh-krishna** [comment]
Might #213 be of some use?

**Comment by noiseredux2** [comment]
Thanks!
