### ISSUE TITLE
Unclear keybindings

### ISSUE THREAD

**Issue by bound-variable** [Cloudef/bemenu#219]
Specifically, what is meant by the keys **delete left**, **delete right**, and **word delete**?

Do people have these keys on their keyboards?

**Comment by RuijieYu** [comment]
I'm looking at the man page right now (v0.6.7) and cannot locate what you are referring -- so maybe your issue has been solved by a recent release. 

Regardless, here are my hypotheses: 
- "delete left" means to delete one char at the left of the cursor (backspace key on keyboard);
- "delete right" means to delete one char at the right of the cursor (delete key on keyboard);
- "word delete" means either to delete one word at the left of the cursor (ctrl-backspace) OR to delete a word at the right of the cursor (ctrl-delete)

**Comment by bound-variable** [comment]
I've resumed use of bemenu, and no longer find these terms in the man page or -h|--help facility.
