### ISSUE TITLE
Set Class for X Backend

### ISSUE THREAD

**Issue by noctuid** [Cloudef/bemenu#22]
It looks like the wayland backend sets the classname, but I don't think the X backend sets any window properties. I think it would be nice to have at least the classname set mainly because I'd like to be able to have bemenu excluded for shadows with compton.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/9110c7c42ec813f4cbf97a1b860009d9cc9a6c0d
