### ISSUE TITLE
-x option no feedback

### ISSUE THREAD

**Issue by flipflop133** [Cloudef/bemenu#221]
The "hide filter text" option (-x, --password) should give feedback to the user in order for the user to
1. Know that what he is typing is recorded
2. Of the number of characters he is typing

Otherwise, the user is typing his password blindly, while the -x option purpose should just be to hide the password.
So a simple way to give feedback would be to print a stars (****) instead of the real input, like a lot of password input fields do.

**Comment by Earnestly** [comment]
Normally password input on all unix systems is blind.

**Comment by flipflop133** [comment]
You are right I get your point, let's not break decades old unix traditions.

**Comment by Earnestly** [comment]
systemd is beginning to use `*` as placeholders for password prompts.

**Comment by wundrweapon** [comment]
Perhaps `-x ` for existing Unix-y behavior and `-X` for stars?

**Comment by Cloudef** [comment]
The -x can also be turned into parameter that takes option similar to --scrollbar

**Comment by Eloitor** [comment]
In addition to this, is there a keybinding to clear everything typed so far in case of a mistake? If not, I think it would be useful to me when using the -x option.

**Comment by Seltyk** [comment]
Ctrl+W, per the manual. Works with `-x`
