### ISSUE TITLE
wl_seat erro

### ISSUE THREAD

**Issue by athrungithub** [Cloudef/bemenu#25]
wl_registry@2: error 0: invalid version for global wl_seat (5): have 4, wanted 5

This line ???  
 wayland->seat = wl_registry_bind(registry, id, &wl_seat_interface, XDG_SHELL_VERSION_CURRENT);
In weston client version is always 1 o 4

**Comment by Cloudef** [comment]
XDG_SHELL_VERSION_CURRENT is mistake there.

**Comment by Cloudef** [comment]
Does https://github.com/Cloudef/bemenu/commit/6b951600aa4477a7fac0b60deedc852c79117715 fix this for you?

**Comment by athrungithub** [comment]
yes. fix
