### ISSUE TITLE
Cannot paste because text/plain;charset=utf-8 (with potential patch)

### ISSUE THREAD

**Issue by RuijieYu** [Cloudef/bemenu#251]
Hello, I tried to paste something copied from emacs, and it refused to paste properly in bemenu.  Upon further inspection and looking at the code, it seems that the clipboard only registered the text as mime type `text/plain;charset=utf-8` (amongst other irrelavent entries), and bemenu only accepts `text/plain` (notably, not `text/plain;charset=utf-8`).

This is what I get after copying from emacs:
```text
user@hostname ~ $ wl-paste -l
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/plain;charset=utf-8
SAVE_TARGETS
```

The following patch removes the `/plain` part of the mime type to accept all `text` mime types. By the literal definition of "text", I think it make sense to assert that bemenu should be able to handle the clipboard content. For reference, the patch is made on 0.6.7 (c3a662d) and should apply cleanly. 

```diff
diff --git a/lib/menu.c b/lib/menu.c
index 1478374..4cb8f01 100644
--- a/lib/menu.c
+++ b/lib/menu.c
@@ -990,7 +990,7 @@ bm_menu_run_with_key(struct bm_menu *menu, enum bm_key key, uint32_t unicode)
         case BM_KEY_PASTE:
             {
                 FILE *clipboard;
-                clipboard = popen("wl-paste -t text/plain", "r");
+                clipboard = popen("wl-paste -t text", "r");
                 if (!clipboard) {
                     clipboard = popen("xclip -t text/plain -out", "r");
                 }
```

Alternatively, we could also pass in multiple `-t MIMETYPE` arguments to `wl-paste` if it is necessary to specify the subtypes. If this is desired, to solve my problem I would replace the first argument `popen` with `"wl-paste -t text/plain -t text/plain\\;charset=utf-8"`.

If this patch is fine, then maybe the xclip part should also be updated, but since I don't run X on my machine, I cannot test for that part. 

Thoughts?

**Comment by Cloudef** [comment]
Probably should use UTF8_STRING as it's the most used I think.

**Comment by RuijieYu** [comment]
Sorry for the late response, somehow your response fell off my radar.

---

> Does wl-paste and xclip allow fallbacks?

First, on your second point -- unfortunately, after some testing, I found out that `wl-paste` only uses the final MIME type from the command line.

```console
$ wl-copy < /usr/share/doc/graphviz/dot.1.pdf
$ wl-paste -l
application/pdf
$ wl-paste -t application/x-pie-executable 2>/dev/null | wc -c
0
$ wl-paste -t application/pdf 2>/dev/null | wc -c
55884
$ wl-paste -t application/pdf -t application/x-pie-executable 2>/dev/null | wc -c
0
$ wl-paste -t application/x-pie-executable -t application/pdf 2>/dev/null | wc -c
55884
```

---

> Probably should use UTF8_STRING as it's the most used I think. (Not sure about wayland though)

Regarding your first point, although it is the most logical for me, it seems that not many applications add this type to their copied contents.  Here below are some tests for MIME types for copied contents accross different applications (where on each application some texts are copied).

Firefox:
- website content
```text
text/html
text/_moz_htmlcontext
text/_moz_htmlinfo
text/plain;charset=utf-8
text/plain
text/plain;charset=utf-8
text/plain
text/x-moz-url-priv
```
- URL
```text
text/plain;charset=utf-8
text/plain
text/plain;charset=utf-8
text/plain
```

Terminal emulators:
- Alacritty
```text
text/plain;charset=utf-8
UTF8_STRING
```
- Kitty
```text
application/glfw+clipboard-522477
text/plain
text/plain;charset=utf-8
TEXT
STRING
UTF8_STRING
```

Chrome-based browser (qutebrowser):
- website content
```text
text/html
text/plain
text/plain;charset=utf-8
```
- URL
```text
text/plain
text/plain;charset=utf-8
```

Emacs
```text
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/plain;charset=utf-8
SAVE_TARGETS
```

VS Code
```text
text/plain;charset=utf-8
text/plain
chromium/x-web-custom-data
text/html
text/plain
text/plain;charset=utf-8
```

I tried to do the same for `xclip` using xwayland, but it seems that `xclip -o -t TARGETS` does not output reasonable MIME types even for contents like PDF files and binary executable files.

---

Going back to my original point, I still think that using a `text` MIME type, at least for wayland, is the best idea: it is able to capture all the above types of copied contents, whereas a `text/plain` MIME type cannot capture Alacritty and Emacs.

I believe the description of `text` MIME type on [Mozilla's website](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) also supports my point that the content should be a human-readable content, and therefore logically should be able to paste into a bemenu prompt.

The reason that I specify Wayland is because of the following quote from `wl-paste`'s manpage:

```markdown
In addition to specific MIME types such as `image/png`,
`wl-paste` also accepts generic type names such as `text`
and `image` which make it automatically pick some offered
MIME type that matches the given generic name.
```

Since in my testing `xclip` does not function properly, I do not know whether the same change would work on xorg -- maybe someone else can test this.

**Comment by Cloudef** [comment]
I think on X11 UTF8_STRING works even if it's not in TARGETS. At least this was my experience when I was doing X11 clipboard stuff. UTF8_STRING is/was pretty much the universal way to get text as UTF8.

**Comment by RuijieYu** [comment]
I have done further tests, which shows that UTF8_STRING is not treated specially in Wayland.  Texts are copied from qutebrowser. 

```console
$ paste_test UTF8_STRING
text/html
text/plain
text/plain;charset=utf-8
0
```

For curiosity, I filed an [issue](https://github.com/bugaevc/wl-clipboard/issues/143) to wl-clipboard asking why `text/plain` currently does not cover MIME types like `text/plain;charset=utf-8`. 

If UTF8_STRING works as a cover-all MIME type for x11, *and* if someone else experiences my issue on x11, I feel it would be justified that we change the MIME type for x11 from `text/plain` to `UTF8_STRING`. 

Regarding the MIME type for Wayland, I want to wait a while for a response in the aforementioned issue.

If they decide that this is an intended behavior (that `text/plain` does not indeed offer `text/plain;charset=utf-8`), then I propose we switch the `text/plain` MIME type to `text` MIME type for Wayland.

If they figure that it is unintended, we would probably just wait for them to update the MIME type handling.

**Comment by ndren** [comment]
@RuijieYu Hi. When I wrote the patch to include clipboard support, I chose text/plain because that was the MIME type that was autocompleted in Bash, not because of any particular preference that this would actually work any better than any other textual type.

I think I agree replacing text/plain with text on Wayland would be a good idea.
