### ISSUE TITLE
`--ch` cursor height option not being applied

### ISSUE THREAD

**Issue by mpahsu** [Cloudef/bemenu#252]
It seems the `--ch` option to change the cursor height is not being applied correctly.

**Steps to reproduce:**
1. `bemenu-run --line-height 32 --ch 16`

**Expected result:**
Cursor to be half of the height of the bemenu line.

**Actual result:**
Cursor is still the full line height.

Screenshot:
![image](https://user-images.githubusercontent.com/3999823/157833372-42735c3d-bdaa-4124-876a-42e6ae3c3b71.png)

**Comment by mpahsu** [comment]
I have raised #253 which I think fixes this.

**Comment by TripleK2004** [comment]
> 1. bemenu-run --line-height 32 --ch 16

This hasn't yet been solved in 0.6.7 ? There is no change in height upon running the above command.
Installed bemenu from community repository, arch linux. `bemenu-wayland` pkg

**Comment by mpahsu** [comment]
> This hasn't yet been solved in 0.6.7 ?

Yeah, I think v0.6.7 was cut on 21 Feb 2022 and this change was merged on 11 Mar 2022. v0.6.7 is the latest release.

@Cloudef: do you know when the next release will be cut for us to get this fix out?
