### ISSUE TITLE
wayland: dpi-aware

### ISSUE THREAD

**Issue by dkwo** [Cloudef/bemenu#254]
Is it possible to make `bemenu` DPI-aware on Wayland?
This is the behavior e.g. of the `foot` terminal emulator:
if I set font to size 12, it will take into account the DPI as advertised by the compositor, and act accordingly.
(I know there's the scaling option, but it seems suboptimal.)

Thanks.

**Comment by Cloudef** [comment]
Wayland backend should already be aware of output's scale

**Comment by dkwo** [comment]
I agree it is aware of scale, but that's not what I'm discussing;
I'm suggesting it could be aware of the output's DPI, which is different.
The compositor has that information, and there should be a way to pick it and pass it to fontconfig/pango.

**Comment by Cloudef** [comment]
Is there protocol that exposes DPI on wayland?

**Comment by dkwo** [comment]
Not directly.

One can use wl_output::geometry and wl_output::mode
to compute DPI, as done e.g. here:
https://codeberg.org/dnkl/foot/src/branch/master/wayland.c#L1294

**Comment by dkwo** [comment]
closing this, as maybe askint too much

**Comment by Cloudef** [comment]
Better keep it open as it's still open issue right?

**Comment by dkwo** [comment]
sure, if one wants the same (optimal) behavior as foot :)
I think, a more important issue to be fixed is the one with scaling: currently, if I use `wlr-randr --output ${ext} --scale 2`, then bemenu font looks blurry. @Cloudef what do you think?

**Comment by Cloudef** [comment]
I think the fractional scaling should cover this perhaps? Feel free reopen if not.
