### ISSUE TITLE
bemenu doesn't stop loading when using custom font

### ISSUE THREAD

**Issue by RiedleroD** [Cloudef/bemenu#255]
This happens when I set the custom font through `-fn` - and it happens with any font.

Problem: bemenu shows the text 'Loading...' until I press any button (even control buttons like Super work). No console output. And the custom font isn't even loaded.

I don't have any font-related issues in any other program, so I'm guessing my fontconfig is fine.

**Comment by Cloudef** [comment]
use `--fn` bemenu doesn't _yet_ support the dmenu "longshort" options.

**Comment by RiedleroD** [comment]
well uh… 3 years of using linux + CLI and I didn't even notice 🤦🏻 

Anyway, now it's being set to my default system font, regardless of what font name I try to set. If I don't set any font, it seems to be using the default monospace font.

**Comment by RiedleroD** [comment]
oh, nevermind. I set the font size with the square brackets instead of without. Works now, thanks for the help.
