### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by EliaHKM** [Cloudef/bemenu#257]
Hi 🙋🏻,
Could you add support to Flatpak apps?

**Comment by Earnestly** [comment]
It already does

**Comment by EliaHKM** [comment]
nothing showed up 
what should I add to bemenu-run to make it showing the flatpak apps

**Comment by Earnestly** [comment]
I don't know flatpak enough to understand what "showing up" means, but here is the workflow: https://github.com/Cloudef/bemenu/blob/master/.github/workflows/flatpak.yml

**Comment by Cloudef** [comment]
I think he means he wants support for xdg-desktop spec. You can combine bemenu with j4-dmenu-desktop for that. 
https://github.com/enkore/j4-dmenu-desktop

**Comment by EliaHKM** [comment]
I'm using sway on EndeavourOS  and I'm not a developer 
what I need here is  when I typed flatseal (flatpak app)
in bemenu text-field that app(flatseal) show up in the list

**Comment by orowith2os** [comment]
Gonna bump this a bit with some more details:

User-installed flatpaks don't show up at all when I execute bemenu-run
System-installed flatpaks seem to work for other people, but I have all of my flatpaks installed in my home folder, so I can't verify this currently.

Displaying the flatpak names (the actual names and flatpak executable name) doesn't seem to work on a majority of launchers I've tried, and krunner has insanely long startup times for some reason, so bemenu having a fix to show flatpaks correctly would be appreciated.

**Comment by aqxa1** [comment]
Just to document the `j4-dmenu-desktop` workaround, here's the command I used in sway's config:

`set $menu dmenu_path | j4-dmenu-desktop --dmenu="bemenu --ignorecase" | xargs swaymsg exec --`

You probably want to use `--ignorecase` as flatpaks seem to start with a capital letter.

But yeah, would still be nice to have this support built in.

**Comment by nful2** [comment]
@Cloudef This works, thanks!

**Comment by S1ngl3-x** [comment]
Sorry for necro, but in case anyone else is searching, running like this works great.

`env PATH=$HOME/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:$PATH bemenu-run`

The only downside is ofc the long names, like org.mozzila.firefox, but it doesn't need any other program to run.
