### ISSUE TITLE
No Output at all from bemenu

### ISSUE THREAD

**Issue by metalune1** [Cloudef/bemenu#264]
I have installed `bemenu` by cloning the git repository and running the compilation commands. Everything seemed to have installed just fine, but when I try to run it with `bemenu` or `bemenu-run` or any number or combination of arguments, nothing happens, the application quits immediately without throwing an error, without printing anything to the console. I have set the environment variable `BEMENU_BACKEND` to `wayland`. 

I thought it was just something related to my sway setup, but it doesn't even print anything to the console when running `bemenu -h` or `bemenu-run -h` to bring up the help pages. I'm running Ubuntu 22.04 with sway installed from the package manager.

**Comment by Cloudef** [comment]
From readme:
```
# To test from source, you have to point the LD_LIBRARY_PATH and BEMENU_RENDERERS variables:
LD_LIBRARY_PATH=. BEMENU_RENDERERS=. ./bemenu-run
```

**Comment by metalune1** [comment]
Alright, I've tried that now, and after running
```bash
LD_LIBRARY_PATH=. BEMENU_RENDERERS=. ./bemenu-run
```

I get this:
```bash
wayland: version  mismatch (0.6.7-81b509155c5c180e02d96f82db4752613bbbd661 != 0.6.7-nogit)
```

**Comment by metalune1** [comment]
Alright, I got it working! For future people who may be curious, here's how I solved the issue:
```bash
# First clean everything I've done before
make clean
sudo make uninstall
sudo make uninstall PREFIX=/usr

# Now reinstall everything with PREFIX=/usr
make PREFIX=/usr
sudo make install PREFIX=/usr


```
