### ISSUE TITLE
Bemenu doesn't show anything on Wayland

### ISSUE THREAD

**Issue by zsolt-donca** [Cloudef/bemenu#271]
I am using bemenu with the Wayland backend, using a recent development build of sway. When invoked, it doesn't show anything, though it seems to receive keyboard events (arrows, enter work). I tried the latest bemenu releases and the latest development versions as well, and it's the same. Note that I'm using fractional scaling.

Using Arch Linux, and using the AUR packages [bemenu-git](https://aur.archlinux.org/packages/bemenu-git) and [bemenu-wayland-git](https://aur.archlinux.org/packages/bemenu-wayland-git).

Steps to reproduce:
1. run in the terminal: `echo "foo\nbar" | bemenu`
2. notice that you don't see any new window pop up or anything
3. press enter
4. notice that you receive `foo` on the terminal

**Comment by RuijieYu** [comment]
Do you know which commit of bemenu and of sway caused the issue you mentioned?  I believe `pacman -Qii bemenu bemenu-wayland sway` should show the commit hashes.  Hopefully this information helps the developer to pinpoint where the issue lies.

**Comment by vonshednob** [comment]
I have the same issue. bemenu is version `v0.6.15`. The exact commit hashes are not shown though.

However, based on the version it should be 752be280a8f41d15195ad2eaebbfd995a0353e68

**Comment by slendermon** [comment]
Can you put in your terminal
`bemenu-run`
