### ISSUE TITLE
support for shell alias

### ISSUE THREAD

**Issue by dkwo** [Cloudef/bemenu#272]
Would it make sense to add the support for shell aliases?
What I mean is that if e.g. my `.bash_rc` contains `alias matica='QT_QPA_PLATFORM=xcb glibc mathematica'`, then I would be able to run the command `matica` in `bemenu-run`.
Thanks.

**Comment by escondida** [comment]
This sounds like a case for writing a li'l wrapper script in your personal bindir rather than using a shell alias; the wrapper will be found by anything that knows about $PATH.

**Comment by dkwo** [comment]
Makes sense, thank you.

**Comment by Earnestly** [comment]
Wrapper scripts always work and in more contexts than just shells; they are superior to aliases or shell functions in every way.
