### ISSUE TITLE
invalid method with latest commit

### ISSUE THREAD

**Issue by deprecated-dot** [Cloudef/bemenu#295]
I updated this morning and bemenu no longer functions. For diagnostic purposes, I ran the base command without any options, and got the following error:

`❯ bemenu-run`

`wl_display@1: error 1: invalid method 9 (since 3 < 4), object wl_surface@14`

Using latest wlroots commit (8026953d)

If I roll back to bemenu 0.6.10, everything functions normally. 

Running on Gentoo 5.19.7 with Sway, if that means anything. If you need further details, please let me know. Thanks for the great software!

**Comment by thomab** [comment]
Manual rebuild fixed it for me.
