### ISSUE TITLE
How to turn off checkered output?

### ISSUE THREAD

**Issue by ephemer4l** [Cloudef/bemenu#298]
I'm not sure if this is the correct way to describe it but since the last update, my bemenu has been showing up checkered (some elements have darker background than others). I couldn't see anything about this in the man page or in the current issues.

[Here](https://i.ibb.co/PhzhZ2Y/screenshot.png)'s an image of what I'm trying to explain. Is there any way to go without this feature?

**Comment by Cloudef** [comment]
0.6.10 should not have the alternating colors by default anymore

**Comment by ephemer4l** [comment]
Thank you!
