### ISSUE TITLE
Not all elements are properly colored

### ISSUE THREAD

**Issue by bound-variable** [Cloudef/bemenu#306]
Shouldn't the background here be all red, while the foreground is white?

![40329](https://user-images.githubusercontent.com/51193876/193375677-eb1aec19-48ac-4325-9655-00de0b3fb224.png)

Compositor: River

**Comment by RayAlto** [comment]
I found it is not documented in manual, run `bemenu-run --help`:
```plain
 --fbb                 defines the feedback background color. (wx)
 --fbf                 defines the feedback foreground color. (wx)
 --ab                  defines the alternating background color. (wx)
 --af                  defines the alternating foreground color. (wx)
```
Add these flags works for me.
