### ISSUE TITLE
Wayland, cant pointer click when builded with env variable CFLAGS

### ISSUE THREAD

**Issue by stacyharper** [Cloudef/bemenu#308]
Hey there,

With this new 0.6.11, when builded with `CFLAGS="…" make, mouse click doest select the entry. Touch release continues to works.

I have no idea why yet. I'll remove this build flag for this release on Alpine Linux recipe

**Comment by Cloudef** [comment]
If -g affects the behavior it sounds like there is undefined behavior in the code

**Comment by stacyharper** [comment]
I edited the issue a bit. CFLAGS="" also trigger this. I tried to tweak the alpine recipe to unset CFLAGS and the issue continues. I'm still looking for the cause

**Comment by stacyharper** [comment]
The issue comes from the fact that `0 & 0` is not recognised as a true operator most of the time. (for a reason I dunno)

```c
    if (event->state & WL_POINTER_BUTTON_STATE_PRESSED) { // when releasing, 0 & 0
        bm_pointer.state |= POINTER_STATE_PRESSED; 
    } 
```

This solve the issue:

```diff
diff --git a/lib/renderers/wayland/wayland.c b/lib/renderers/wayland/wayland.c
index f5bb33d..4424b46 100644
--- a/lib/renderers/wayland/wayland.c
+++ b/lib/renderers/wayland/wayland.c
@@ -270,10 +270,9 @@ poll_pointer(const struct bm_menu *menu)
     }
 
     if (event->state & WL_POINTER_BUTTON_STATE_PRESSED) {
-        bm_pointer.state |= POINTER_STATE_PRESSED;
-    }
-    if (event->state & WL_POINTER_BUTTON_STATE_RELEASED) {
-        bm_pointer.state |= POINTER_STATE_RELEASED;
+        bm_pointer.state = POINTER_STATE_PRESSED;
+    } else {
+        bm_pointer.state = POINTER_STATE_RELEASED;
     }
 
     memset(event, 0, sizeof(*event));
```

I added this to debug and it gave a very unexpected outcome:

```diff
+    if (0 & 0)
+        fprintf(stderr, "foo\n");
+    if (1 & 1)
+        fprintf(stderr, "bar\n");
+
     if (event->state & WL_POINTER_BUTTON_STATE_PRESSED) {
         bm_pointer.state = POINTER_STATE_PRESSED;
     } else {

```

```
bar
bar
bar
foo
```

**Comment by Cloudef** [comment]
is bm_pointer.state initialized?

**Comment by Cloudef** [comment]
The issue is that, https://github.com/Cloudef/bemenu/blob/8217ae024b539a3cecfc77fc3b9c186f6c563753/lib/renderers/wayland/wayland.c#L251 bm_pointer struct isn't initialized, this should be initialized with `= {0}`
Though I don't think it makes sense for bm_pointer.state to be a bitflag as how can pointer be both released and pressed?

**Comment by stacyharper** [comment]
Ah you right. Initializing correctly fix the issue.

About the fact we use a bitflag, I used that cause `wl_pointer_button_state` is an enum. Atm there is only two values `WL_POINTER_BUTTON_STATE_RELEASED` and `WL_POINTER_BUTTON_STATE_PRESSED` but I guess it has been designed to be extendable.

**Comment by Cloudef** [comment]
The enum values do not seem to be bitflags though. Otherwise they would be specified as 1<<0, 1<<1 and so on ...
