### ISSUE TITLE
Bemenu on arch package no longer downloadable

### ISSUE THREAD

**Issue by jiiiijiij** [Cloudef/bemenu#313]
Pacman can't retrieve the package no more, look like the download form mirror working find

**Comment by Cloudef** [comment]
Not a bemenu issue

**Comment by escondida** [comment]
Make sure that you run a full update (`pacman -Syu bemenu`; you can also add any or all of bemenu-ncurses, bemenu-wayland, and bemenu-x11 to that command): 0.6.13 is available in [community], and if you're working with an older local db your system is likely trying to fetch the previous version.

If updating your system while installing doesn't work, try a different mirror; yours is likely out-of-date.
