### ISSUE TITLE
Rounded corners / border radius possible?

### ISSUE THREAD

**Issue by revuwa** [Cloudef/bemenu#319]
Thanks for [this PR](https://github.com/Cloudef/bemenu/pull/265) ❤️

Because I tried to visually align bemenu in my [Hyprland](https://github.com/hyprwm/Hyprland) environment, I wondered if there is a way to get rounded (border) corners?
My current view is this: 
![image](https://user-images.githubusercontent.com/7300276/202860684-5a02f1db-e913-42e1-9d5f-37d8604ba8e7.png)

It would be so great if bemenu have, or possibly could get such an option. What do you think?

**Comment by dynamicdotvoid** [comment]
It seems to be possible, I can look into making a PR request once I get it working.

**Comment by revuwa** [comment]
Thanks a lot - all of you 🚀
