### ISSUE TITLE
Border Missing on Right Side

### ISSUE THREAD

**Issue by fictitiousexistence** [Cloudef/bemenu#321]
bemenu v0.6.13

Border is appliying all around bemenu except for the right side. 

`bemenu -b -l 10 -p ">>>" --tf "#f25805" --hf "#ff0000" --bdr "#ff0000" --nf "#f25805" --af "#f25805" --fn "Code New Roman" -B 5 -M 4`

![bemenu](https://user-images.githubusercontent.com/20089581/206878510-03073c68-a183-415b-b514-925f77e83157.png)

**Comment by dynamicdotvoid** [comment]
The command seems to work fine for me. Could we get more details(distro, specs, window manager, etc)?

**Comment by fictitiousexistence** [comment]
I upgraded to v0.6.14 and its working now. Thanks.

**Comment by stacyharper** [comment]
I also relate this on master

**Comment by stacyharper** [comment]
`seq 1 4 | LD_LIBRARY_PATH=. BEMENU_RENDERERS=. ./bemenu --fixed-height -l5 -B50`

![2023-02-21-15-41-47](https://user-images.githubusercontent.com/14213590/220375724-134a175a-63aa-48cb-8c89-a44f8b875b25.png)

It looks a little bit better with this change:

![2023-02-21-15-42-44](https://user-images.githubusercontent.com/14213590/220375910-5a19f510-65a4-451a-9e33-f873b1b4ded7.png)

```c
diff --git a/lib/renderers/cairo_renderer.h b/lib/renderers/cairo_renderer.h                                                                                    
index e021b53..0b1d6ce 100644
--- a/lib/renderers/cairo_renderer.h
+++ b/lib/renderers/cairo_renderer.h
@@ -509,9 +509,9 @@ bm_cairo_paint(struct cairo *cairo, uint32_t width, uint32_t max_height, const s
     bm_cairo_color_from_menu_color(menu, BM_COLOR_BORDER, &paint.fg);
     cairo_set_source_rgba(cairo->cr, paint.fg.r, paint.fg.b, paint.fg.g, paint.fg.a);
     if (!border_radius) {
-        cairo_rectangle(cairo->cr, 0, 0, width + border_size, (height * (page_length + 1)) + (2 * border_size));
+        cairo_rectangle(cairo->cr, 0, 0, width/cairo->scale + border_size, (height * (page_length + 1)) + (2 * border_size));
     } else {
-        bm_cairo_draw_rounded_path(cairo->cr, 0, 0, width + border_size, (height * (page_length + 1)) + (2 * border_size), border_radius);
+        bm_cairo_draw_rounded_path(cairo->cr, 0, 0, width/cairo->scale + border_size, (height * (page_length + 1)) + (2 * border_size), border_radius);
     }
     cairo_set_line_width(cairo->cr, 2 * menu->border_size);
     cairo_stroke(cairo->cr);
```

But the right border still is thinner than the others
