### ISSUE TITLE
bemenu causing sway to crash on empty workspace

### ISSUE THREAD

**Issue by ppascher** [Cloudef/bemenu#34]
Not sure if I should raise this issue here or with sway.
When I try to launch a program via bemenu in an empty workspace sway (git) crashes. If there is another window already opened it works fine. Sway exits back to console with a segfault. I tried enabling sway debug  but could not find any error.
It used to work fine about a week or two ago (I can try to find the exact commit which started this).
I am using the wayland backend.

**Comment by Cloudef** [comment]
pinging @martinetd @SirCmpwn

**Comment by martinetd** [comment]
Definitely a sway problem, sway shouldn't crash even if bemenu were to actively try to crash it!
I just tried on latest master and cannot reproduce, but get a crash a few commits earlier, so I guess it already got fixed.

Please update sway and if it still happens get a backtrace for the sway crash (coredumpctl gdb; bt full) -- once you have that backtrace look for recent tickets there and try to fix it.

**Comment by ppascher** [comment]
You are right. It is not happening anymore on latest sway git. Closing this.
