### ISSUE TITLE
Display of selected item lags behind

### ISSUE THREAD

**Issue by ppascher** [Cloudef/bemenu#35]
I use bemenu (bemenu-git from AUR) with sway using the wayland backend and open it using mod+d. When trying to launch for example "playonlinux" the sequence is as follows:

Key Pressed - Displayed Value - Displayed list
p - (NULL) - (everything)
pl - p - p11-kt, p11tool....
pla - pl - pl2pm, play, playonlinux
play - pla - play, playonlinux
playo - play - play, playonlinux

Now when I hit enter "playonlinux" is run although "play" is marked as the active entry. So it seems only the display lags behind by one while intenally everything is correct.

**Comment by Cloudef** [comment]
Can you try if it works okay with xwayland/x11?

**Comment by ppascher** [comment]
Can't seem to get it to run using x11 backend (returns 1). I build wlroots with both xwayland and x11-backend enabled, sway with xwayland enabled. (ncurses works fine btw).

**Comment by lcges** [comment]
I have exactly the same as @ppascher 
Terrible lagging while typing, to write the text you have to write very quickly.

**Comment by ppascher** [comment]
For me it is not really lag as in delay (it does not matter how fast I type) but more a 'off by one' problem. Not sure if it is wlroots/sway which should redraw and does not (missing damage?) or if it is a problem with bemenu wayland backend.

**Comment by Cloudef** [comment]
If it does that on weston too, then it's most likely problem in bemenu's window.c.
