### ISSUE TITLE
bemenu-run fails: "wayland: mmap failed" , "could not get next buffer"

### ISSUE THREAD

**Issue by Manfred-Knick** [Cloudef/bemenu#370]
Please c.f. description at Gentoo Bug 917133 :
https://bugs.gentoo.org/show_bug.cgi?id=917133

**Comment by fictitiousexistence** [comment]
Ran into the same issue. 
I reverted wayland and wayland-protocols back but still got the same error. 

It seems commit c22cc64 is causing the issue. 

Bemenu works again after rebuilding with commit eb92e7b.

**Comment by fictitiousexistence** [comment]
Whoops, accidentally had some old wlroots install from hyprland on my system that was conflicting. Never needed to downgrade wlroots.

But https://github.com/Cloudef/bemenu/pull/368 does fix the issue.

**Comment by Manfred-Knick** [comment]
#368: commit 62657f8 has been merged
Just tested with
[IP-] [  ] x11-drivers/nvidia-drivers-545.29.02:0/545
[IP-] [  ] gui-libs/wlroots-9999:0/9999
[IP-] [  ] x11-base/xwayland-9999:0
[IP-] [  ] gui-wm/dwl-9999-r1:0
[IP-] [  ] dev-libs/bemenu-9999:0
