### ISSUE TITLE
bwindow doesn't work on sway

### ISSUE THREAD

**Issue by zzzeyez** [Cloudef/bemenu#378]
`> bwindow 
gojq: invalid json: <stdin>
 HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
 ^ invalid character 'H' looking for beginning of value 
gojq: invalid json: <stdin> HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
 ^ invalid character 'H' looking for beginning of value`

when i try to use `bwindow` on sway i get the above error message.  works great in hyprland though.  running latest of all software via arch

**Comment by Cloudef** [comment]
I'm not sure what bwindow is?

**Comment by zzzeyez** [comment]
LOLL omg i had forgot it was a script i made myself using bemenu (alt-tab switcher).  i am so sorry.

**Comment by Cloudef** [comment]
Np
