### ISSUE TITLE
fallback to shell execution

### ISSUE THREAD

**Issue by LaptopDev** [Cloudef/bemenu#387]
Can bemenu execute user input through shell if user presses enter with no matches?
I thought I was getting my alias to work before with bemenu but it's not now. 
`alias thunderbird='flatpak run org.mozilla.Thunderbird'`

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/issues/272

**Comment by LaptopDev** [comment]
> #272

I don't think that's what I am asking. If it is, I couldn't see how based on the lack of examples in the linked issue.

**Comment by Cloudef** [comment]
bemenu-run will not parse shell rc files, or add any sort of integration with the shell. However if you are fine with the input being piped to shell with no listing support then you can do something along:
```sh
bemenu-run --no-exec |  ${SHELL:-"/bin/sh"}
```
(Might need -l or -i flag for the SHELL for it to pick up your aliases)

**Comment by LaptopDev** [comment]
@Cloudef Would 
`bemenu-run --no-exec |  ${SHELL:-"/bin/sh"}`

 still allow partial matches to be executed?

**Comment by CIAvash** [comment]
It seems `Shift+Return` can be used for that

**Comment by CIAvash** [comment]
`Shift+Return` is the opposite of that, I think, executes the filter. `Return` executes the first result.

**Comment by LaptopDev** [comment]
not sure what shift return does... but I found cloudef's suggestion does work for me, executing partial matches, which I tested.

This is my new bind (hyprland):
`bind = $mainMod, p, exec, bemenu-run --binding vim --fn 'monospace 20' --no-exec |  ${SHELL:-"/bin/sh"} -i`

thanks for the help
