### ISSUE TITLE
I'm having issues setting colors

### ISSUE THREAD

**Issue by tristengrant** [Cloudef/bemenu#393]
I saw a previous issue where someone had problems setting colors. I followed what fixed it for them, for example: **--fb="#ff0000"** but that doesn't seem to work for me, on Hyprland. 

Everything else seems to work, so I assume its something I'm doing wrong. If I do use the same example as before, if I have the # in the hex code, bemenu doesn't run at all. If I don't put the #, the colour still doesn't change from its default. Same thing if I try an rgb value.

Is there a config file somewhere we can change?

The exact settings I'm using in my hyprland config for bemenu 

``bemenu-run --fn='JetBrains Mono Bold 11.5' --fb='#ff0000' --ch='21' --cw='2.5' --hp='10' --auto-select --wrap --fixed-height --accept-single --single-instance  --prompt 'RUN:' --fixed-height --line-height '30'``

**Comment by Cloudef** [comment]
bemenu colors require 4 components, for example #121212FF

**Comment by tristengrant** [comment]
Hmm, yeah its probably because of the config. Do you know of a different way to run it?

**Comment by Cloudef** [comment]
You can either set BEMENU_OPTS (you need to pass long args without '=') env variable, or creating wrapper script

**Comment by tristengrant** [comment]
Ah, perfect. Thank you! I write a simple script but the double # works as well. Thanks again!
