### ISSUE TITLE
Border woes

### ISSUE THREAD

**Issue by Erothas** [Cloudef/bemenu#399]
![image](https://github.com/Cloudef/bemenu/assets/55455670/f1535a08-fe4d-4015-9603-72707a99f449)

This is the command I used: `j4-dmenu-desktop --dmenu='bemenu --single-instance -i -l 10 -H 25 -M 850 --tb "#191622" --tf "#e534ebff" --fb "#191622" --ff "#94e2d5" --nb "#191622E6" --nf "#ffffffff" --hb "#e534ebff" --hf "#ffffffff" --ab "#191622E6" --af "#ffffffff" --fn FiraSans --bdr "#e534ebff" -B 2 -R 20'`

So, there are two issues that you could probably already spot right away: 

1. The border is being drawn over the background, leading to the background's colour bleeding over/under.
2. The border is very clearly jagged. The thicker the border, the worse it becomes as well.

**Comment by Cloudef** [comment]
Is this better on HEAD?

**Comment by Erothas** [comment]
Sorry for getting back to you late. Truth be told, I was sick and tired of everything on hyprland (including the WM itself) being jank and a buggy mess. So, I uninstalled it all, and installed KDE instead. However, just for you, I installed everything back, and fully updated my system. I then tried out bemenu.. and hyprland instantly crashed... I logged back in, made a second attempt at invoking bemenu. Hyprland crashes again... 

Yeah, I am done with this. Until my life allows for it again (which could be sooner than I think), I don't have time to troubleshoot, trace and run after crash reports anymore.

**Comment by Cloudef** [comment]
Can you run the bemenu on the KDE? Doesn't have to be hyprland.

**Comment by Erothas** [comment]
I am dumb. Yeah, even installing something temporary in NixOS is as simple as `nix-shell -p bemenu`.

So yeah, it's perfect now. All the problems I noticed have been resolved. Even including the silly bubbly animation that used to happen with bemenu's launch is gone. Thank you!
