### ISSUE TITLE
Cannot get bemenu to be transparent

### ISSUE THREAD

**Issue by UtkarshVerma** [Cloudef/bemenu#403]
I want to set an alpha for bemenu's background to achieve that glassy look. Setting any value for A in RGBA for normal background, but I can't get it to be translucent.

Setting A to 00 just gives me a black background instead of completely  making bemenu see-through. Is it possible?

**Comment by Xgames123** [comment]
Works for me on v0.6.9 and master using --nb #000000

**Comment by Xgames123** [comment]
Also works with BEMENU_BACKEND="x11"
