### ISSUE TITLE
BG rendering issue 0.6.22

### ISSUE THREAD

**Issue by stacyharper** [Cloudef/bemenu#412]
Hey there,

with this new release, I see transparent lines between entries:

![2024-07-08-08:53:05](https://github.com/Cloudef/bemenu/assets/14213590/ccb3fc97-7dc5-40cb-a551-94bf72db1fcc)

This seems to be caused by $BEMENU_WL_FRACTIONAL_SCALING.

I'm using a 1920x1080 output, scaled 1.4.

**Comment by stacyharper** [comment]
seems caused by: 1201340675bae87a24385bd2b391865a0bd055fc

I had switched it off. What was the reason to revert this?

**Comment by Cloudef** [comment]
Hello, that change originates from this PR https://github.com/Cloudef/bemenu/pull/407

**Comment by stacyharper** [comment]
> Perhaps the antialias should be set to none in fractional scaling case or be a tunable.

Maybe. IMO this require for the backend to expose a new attribute for this

**Comment by Cloudef** [comment]
I'm fine with that. If you can fix it I'll make new release ASAP (might have delay as I'm gonna be on 13h flight soon)

**Comment by stacyharper** [comment]
I'll fix this this evening
