### ISSUE TITLE
segfault when scrolling in "up" mode

### ISSUE THREAD

**Issue by larsch** [Cloudef/bemenu#417]
Steps to reproduce:

Pipe any 20+ lines into bemenu like this:

```sh
find /tmp | bemenu -l "20 up"
```

Hold PageDown until top is reached. Then bemenu segfaults. Only happens in "up" mode, not "down" mode.

I'm on wayland.

Also, PageDown/Up are reversed in "up" mode.

**Comment by Cloudef** [comment]
Should be fixed now

**Comment by 20NE** [comment]
Sorry for issue here.

Same on wayland,  bemenu 0.6.23

selection highlight the wrong line in "up" mode.
no problem in "down" mode.
 in "up" mode, bemenu just highlight the position the selected line suppose to be in "down" mode.

#418
