### ISSUE TITLE
Do not wait for initial wayland events when starting up

### ISSUE THREAD

**Issue by ammen99** [Cloudef/bemenu#42]
I have tried running bemenu on Wayfire (a wlroots based compositor which supports layer-shell). However the `bemenu-run` didn't do anything visible. After a bit of debugging, I think I found the reason: the wayland backend waits for a wayland event before drawing the first frame. In some compositors though no such event will happen before the surface is mapped. Thus I think something along the lines should be implemented:

```
diff --git a/lib/renderers/wayland/wayland.c b/lib/renderers/wayland/wayland.c
index dd97009..8c18b62 100644
--- a/lib/renderers/wayland/wayland.c
+++ b/lib/renderers/wayland/wayland.c
@@ -13,6 +13,7 @@
 #include <sys/timerfd.h>
 
 static int efd;
+static int firstLoop = 1;
 
 static void
 render(const struct bm_menu *menu)
@@ -26,6 +27,16 @@ render(const struct bm_menu *menu)
     }
 
     struct epoll_event ep[16];
+    if (firstLoop)
+    {
+        struct window *window;
+        wl_list_for_each(window, &wayland->windows, link) {
+            bm_wl_window_render(window, wayland->display, menu);
+        }
+        firstLoop = 0;
+        return;
+    }
+
     uint32_t num = epoll_wait(efd, ep, 16, -1);
     for (uint32_t i = 0; i < num; ++i) {
         if (ep[i].data.ptr == &wayland->fds.display) {
```

This is of course just a hack, I am not familiar with the codebase enough to write a proper solution.

**Comment by Cloudef** [comment]
#40 is slightly related, as it may fix this issue as well, but break key repeats maybe. (Not sure on what function it will block then, maybe wl_display_dispatch()?).
There's really no standard how and when what works with different wayland compositors, so I leave up to you what to do here.
