### ISSUE TITLE
Bemenu not showing in Gnome

### ISSUE THREAD

**Issue by GabrielCardi** [Cloudef/bemenu#424]
### Discussed in https://github.com/Cloudef/bemenu/discussions/423

<div type='discussions-op-text'>

<sup>Originally posted by **GabrielCardi** August 28, 2024</sup>

Hello

I have a simple menu in Bemenu (version 0.6.23) that works fine in Hyprland but does not show anything in Gnome.

I have Gnome 46 on Fedora 40, with Wayland.

Any idea on why that happens?
thx
</div>

**Comment by Cloudef** [comment]
I don't think gnome supports the wlr layer shell protocol

**Comment by GabrielCardi** [comment]
Thanks. I will have to switch to a competitor, then.
