### ISSUE TITLE
[Question] How do I make bemenu only show desktop files?

### ISSUE THREAD

**Issue by bps86** [Cloudef/bemenu#429]
So I recently switch from i3 dmenu to sway fuzzel. But since fuzzel felt terrible for me at searching apps, I decided to try bemenu. The search is much better, but there's only one problem. How do I make it only show .desktop files like i3-dmenu-desktop? I've tried to search from issues and forums and no one talks about it, so I'm at loss right now.

**Comment by Cloudef** [comment]
Afaik you can use j4-dmenu-desktop with bemenu https://github.com/Cloudef/bemenu/issues/62

**Comment by bps86** [comment]
Understood, Thanks for the help,

**Comment by bps86** [comment]
Question answered
