### ISSUE TITLE
[Bug] bemenu defocus/cannot type after right clicking waybar tray icon

### ISSUE THREAD

**Issue by bps86** [Cloudef/bemenu#430]
bemenu Version: 0.6.14
Distro: Debian 12.7
Window Manager: sway 1.7
Bar: waybar 0.9.17

Reproduce steps:
1. Add applet/icon tray on waybar(most common used are nm-applet from network-manager-gnome or obs).
2. Right click on the applet/icon tray.
3. Open bemenu-run with sway keybind(ex: $mod+d)

Expected Result: waybar closes right-click menu opened from applet/icon tray and keyboard focuses on bemenu.
Actual Results: waybar right-click menu doesn't close and keyboard doesn't focus on bemenu, focuses on current focused window instead.

**Comment by Cloudef** [comment]
Bemenu can't control its focus on wayland, I think this is a sway issue.

**Comment by bps86** [comment]
Oh, Understood. I'll report it to them. Thanks,
Attaching issue on sway github: https://github.com/swaywm/sway/issues/8402
