### ISSUE TITLE
bemenu is shown behind waybar

### ISSUE THREAD

**Issue by oblique** [Cloudef/bemenu#45]
bemenu is show behind waybar:
![screenshot_2019-03-19_21:21:59 697946539](https://user-images.githubusercontent.com/194040/54635635-50536e80-4a8d-11e9-8272-af2b6a904573.png)

I'm using the default configuration of [waybar](https://github.com/Alexays/Waybar).

Let me know if you need anything else.

**Comment by Cloudef** [comment]
this is a compositor specific issue (or issue with the protocol waybar/bemenu uses), bemenu can't control where and how it appears under wayland, apart from what the protocol it uses allows.

**Comment by brunelli** [comment]
Replacing `"layer": "top"` with `"layer": "bottom"` in waybar's config file solves this.

**Comment by oblique** [comment]
I can confirm this. Thanks!

**Comment by ammen99** [comment]
I think a proper solution would be changing how bemenu interacts with panel surfaces. We can tell the compositor to move the menu window just below the panel(s) by setting exclusive zone to 0.

 Cloudef would you merge such a PR, as this will slightly change the behavior of bemenu?

**Comment by YorozuyaDev** [comment]
set layer to bot in waybar works but icon tray menu get overlapped by windows, is there a way to set bemenu overlap waybar?

**Comment by oblique** [comment]
My current solution is `"layer": "top"` in waybar config and `-n` argument for bemenu.

**Comment by YorozuyaDev** [comment]
> 
> 
> My current solution is `"layer": "top"` in waybar config and `-n` argument for bemenu.

but this only put bemenu over waybar
