### ISSUE TITLE
Running from source fails silently

### ISSUE THREAD

**Issue by cole-h** [Cloudef/bemenu#51]
I'm trying to build and run bemenu from source on Wayland. Building with `cmake -DBEMENU_WAYLAND_RENDERER=ON ..` works fine, but running it with `dmenu_path | client/bemenu` just has it exit (`echo $?` == 1) with no output. I tried using `gdb` and found that `bm_init()` fails at `lib/library.c:137`. Using 0.1.0 straight from the Arch repositories works fine.

If I were more fluent in C, I'd try to debug further, but this is the extent of my abilities.

**Comment by Cloudef** [comment]
You need to point BEMENU_RENDERERS in the local build renderers directory.

**Comment by cole-h** [comment]
That did it! The reason the AUR git package wasn't working was because Wayland wasn't configured in its `cmake` line. Adding that part manually fixed it up real nice. Thanks for the help.
