### ISSUE TITLE
Undefined symbol errors after #52

### ISSUE THREAD

**Issue by DarkDefender** [Cloudef/bemenu#53]
Build works fine but when trying to launch bemenu, it errors out for me with "undefined symbol" from pango for the x11 backend and wl_surface_interface for the wayland backend.

I'm using gentoo linux.

If I roll back to before #52, it launches and works as expected after building

**Comment by Cloudef** [comment]
I think this commit should be reverted https://github.com/Cloudef/bemenu/pull/52/commits/620ae690209a36b680524f4a4d8bec2f464f05fa using absolute paths doesn't make much sense anyways. Prepend to the search path if you want to prefer different location. What do you think @t6 ?

**Comment by t6** [comment]
Just reverting 620ae69 will break the FreeBSD build and runtime again.  The build should not be assuming that things live in /usr/lib or other search paths otherwise there is little point in even looking things up with pkg-config/cmake. I guess we need to use `target_link_directories` with `x_LIBRARY_DIRS` then.

@DarkDefender Can you please test if #54 works for you?

**Comment by DarkDefender** [comment]
@t6 I'm getting build errors with that:
```
-- Checking for one of the modules 'pango pangocairo'
CMake Error at lib/renderers/x11/CMakeLists.txt:8 (TARGET_LINK_DIRECTORIES):
  Unknown CMake command "TARGET_LINK_DIRECTORIES".
```

**Comment by t6** [comment]
Sigh, ok. Do you use cmake < 3.13?

Regarding using absolute paths for libraries. CMake documentation itself advocates for it:
> This command is rarely necessary and should be avoided where there are other choices. Prefer to pass full absolute paths to libraries where possible, since this ensures the correct library will always be linked. The find_library() command provides the full path, which can generally be used directly in calls to target_link_libraries().

per https://cmake.org/cmake/help/v3.14/command/target_link_directories.html?highlight=target_link_directories

**Comment by DarkDefender** [comment]
Yes, I am on cmake 3.9.6.

**Comment by t6** [comment]
Hmm, so I'm out of ideas and time. Anything I'd propose will probably not work with that old of a cmake. If supporting old cmake versions is important then 620ae69 should probably be reverted.

**Comment by Cloudef** [comment]
I would also be fine by ditching cmake and just going with plain make + pkg-config. Cmake honestly sucks and makes dependencies just harder for everyone.

**Comment by DarkDefender** [comment]
I'm fine with whatever as long as I can build it :P

**Comment by Cloudef** [comment]
I revert https://github.com/Cloudef/bemenu/commit/620ae690209a36b680524f4a4d8bec2f464f05fa for now

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/5a4d364d50b9ca6907de11f201b451e22aa02b85 Should fix this. @t6 BSD build probably won't work out of box now, but if you can check if doing `make LDLIBS=-lepoll-shim` (or using pkg-config if .pc exists for it), and if so document the steps needed for BSD in the readme.
