### ISSUE TITLE
[Wanted] - Documentaion/build from source instruction

### ISSUE THREAD

**Issue by samerickson** [Cloudef/bemenu#55]
Hello, I am running bemenu through the default `pacman` package, and I have found that there is no man pages related to the project, and some information on how the program can be installed from source.

I have tried running:
```
cmake .
make
sudo make install
```

Which results in the error:
```
bash: /usr/bin/bemenu-run: no such file or directory
```
Any information on how I can get started with this would be awesome. Thank you for your time.

**Comment by Cloudef** [comment]
You could check https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/bemenu the PKGBUILD of arch package to see how it builds and installs it. You don't need the DESTDIR of course. Installing to /usr without a package manager is frowned upon though. Default location is /usr/local.

**Comment by CameronNemo** [comment]
/usr is fine as long as you have checkinstall.
