### ISSUE TITLE
 error while loading shared libraries: libbemenu.so.0

### ISSUE THREAD

**Issue by ScottEric** [Cloudef/bemenu#63]
I built this on Fedora 30, the build goes without problem, but when I run bemenu I get the error:

``` error while loading shared libraries: libbemenu.so.0: cannot open shared object file: No such file or directory```
Any advice is appreciated.

**Comment by godfrey-cw** [comment]
Same issue here.

**Comment by Cloudef** [comment]
How does the install tree look like? Running from the build directory?

**Comment by lmartinez2019** [comment]
I get the same error, but the library is compiled on my machine.`libbemenu.so.0` is a symlink that points to `libbemenu.so.0.1.0`. Is this a linker issue?

**Comment by Earnestly** [comment]
Are all of you running Fedora?

**Comment by Cloudef** [comment]
If you are building it locally, and running locally. Make also sure that the `BEMENU_RENDERERS` points to the `renderers` directory in the build tree. Otherwise it will try to load them from system path.

**Comment by lmartinez2019** [comment]
@Earnestly I'm building on Ubuntu 19.04. Runnning `ldd` for the local build of `bemenu` prints:
```
	linux-vdso.so.1 (0x00007fffa29ff000)
	libbemenu.so.0 => /home/USER/.bin/sway-related/bemenu/build/lib/libbemenu.so.0 (0x00007ff18ea6b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff18e862000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff18e85c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff18ea83000)
```

But `ldd` on the installed build of `bemenu` shows `not found` for `libbemenu.so.0`. The only build flags I've used is to explicitly enable the Wayland renderer, and *only* the Wayland renderer.

@Cloudef Is `BEMENU_RENDERERS` an environment variable? I wasn't aware that we had to set that. I've also noticed that while `libbemenu.so.0` is in my `/usr/local/lib`, it's not being used by the installed build. This could be because I don't have that directory in my PATH.

**Comment by Earnestly** [comment]
Yeah, if you're going to install to a location like that you may have to update `ld.so.conf.d/local.conf` with `/usr/local/lib64` or whatever the `lib` directory is.  Or use `LD_LIBRARY_PATH=/usr/local/lib64`.

**Comment by montvid** [comment]
This works on debian as libbemenu.so.0 is in my /usr/local/lib. Add to sway config this:
`set $menu LD_LIBRARY_PATH=/usr/local/lib/ bemenu-run | xargs swaymsg exec --`

**Comment by 3kynox** [comment]
@montvid Thanks, works well with my arch-armv8-64

**Comment by rileyrg** [comment]
FYI, naive install following the instructions on debian 11 and the same issue.

**Comment by florentcigolotti** [comment]
@montvid it is working thanks!

If you don't mind adding `/usr/local/lib` to the list of linker's lib path, you can also add the path to `/etc/ld.so.conf` or even better create a dedicated conf file in `/etc/ld.so.conf.d` (make sure `/etc/ld.so.conf` includes `.conf` files in this directory with: `include /etc/ld.so.conf.d/*.conf`). Then you regenerate the linker cache with `sudo ldconfig`:

```
cat << EOF | sudo tee /etc/ld.so.conf.d/usr-local.conf
/usr/local/lib
EOF
sudo ldconfig
```

Then, check if `/usr/local/lib` is in the linker cache with `ldconfig -p` and check if the lib `libbemenu.so.0` is found with `ldd $(which bemenu`! And you can then remove `LD_LIBRARY_PATH=/usr/local/lib` to your Sway config:

```
set $menu bemenu-run | xargs swaymsg exec --
```

Tested on Arch with `make && sudo make install`

See https://man7.org/linux/man-pages/man8/ldconfig.8.html for more info.
