### ISSUE TITLE
Key repeat doesn't work with Wayland

### ISSUE THREAD

**Issue by alexf91** [Cloudef/bemenu#66]
I am using Sway and I have tried the latest Github version and the release of bemenu.

Some comments mention that this has worked before, so I was looking for the commit that broke it, but I couldn't find a good commit to begin with.

**Comment by ynakao** [comment]
Maybe I have the same issue. I bind `$mod+d` as `BEMENU_BACKEND=wayland bemenu-run` in sway config. While bemenu works fine with [sway v1.2](https://github.com/swaywm/sway/releases/tag/1.2) (released Aug 27),  doesn't work properly with sway built from the latest commit.

I also tried to exec `$ bemenu` and `$ bemenu-run` in terminal, but nothing happened.

**Comment by Cloudef** [comment]
>Edit: Oh, bemenu built from the latest commit works fine with the latest sway build. It might be good to release a minor update version.

I agree, there's been quite few good improvements and fixes as well

**Comment by Cloudef** [comment]
I released new version.
