### ISSUE TITLE
bemenu hidden behind way-bar on sway launch

### ISSUE THREAD

**Issue by AndreVallestero** [Cloudef/bemenu#67]
Immediately after launching sway, if bemenu is launched using a hotkey, it will be hidden behind waybar. It will only appear once another window is opened or if the desktop is clicked.

Note, I have waybar and bemenu attached to the bottom of the screen.

This behavior seems to only occur after first boot. Exiting the sway session and starting it again does not result in this behavior. Similarly, logging out and logging in again does not result in this behavior.

**Comment by metalune1** [comment]
How did you solve this?

**Comment by ulysses4ever** [comment]
Switching to `"layer": "bottom"` worked for me too, that's in waybar's config file. I use waybar and bemenu at the top btw.
