### ISSUE TITLE
Signing with a new GPG key?

### ISSUE THREAD

**Issue by escondida** [Cloudef/bemenu#69]
Thanks as always for your work on this, Cloudef!

The signature file for 0.2.0 seems to be done with key 0x0CBD2CD395613887, whereas previously it was 0xF769BB961AF6D26A. Before I build this update for Arch, can you confirm your new key with your old one (and send it to keyservers) and/or link to some canonical spot on your own site where it can be found?

**Comment by Cloudef** [comment]
Hi,

Yeah. I used new key. I recently moved to japan and my main pc (or well
hdd) is still at finland, so i decided to just generate a new key for now.

I submitted the new key to keyservers.

**Comment by escondida** [comment]
Congratulations on your move! I hope it's going well for you.

Just for the sake of paranoia, for lack of the old key to sign the new one with is there any way you could put some verification of that on your non-github site? If so, I'd appreciate it.

Thanks again, and enjoy Japan!

**Comment by Cloudef** [comment]
You can find it now from here: https://cloudef.pw/pgp.txt
I'll eventually recover my old PGP key (from my old hard drive) as well, whenever I visit Finland again, and sign the new key with the old one and switch using the new one completely.

**Comment by escondida** [comment]
Thanks for uploading your key! Unfortunately, something's gone sideways with the signature on that release even with the new key ("bad signature from public key 0CBD2CD395613887")

**Comment by maximbaz** [comment]
@Cloudef if you are generating the archive in order to sign it with your key, make sure to use the command below to do so, to get the exact archive as Github is generating, otherwise the signature will not match:

```
git archive -o "bemenu-0.2.0.tar.gz" --format tar.gz --prefix "bemenu-0.2.0/" "0.2.0"
```

**Comment by Cloudef** [comment]
Can you try again?

**Comment by maximbaz** [comment]
It's good now 👍

**Comment by Cloudef** [comment]
👌
Did it drunk last time so i probably signed a wrong tarball or something

**Comment by dpeukert** [comment]
ping @escondida, 0.3.0 is now out

**Comment by Cloudef** [comment]
PGP changed, see details here: https://github.com/Cloudef/bemenu/issues/173
