### ISSUE TITLE
RFE: Option for dmenu-like indent items in list mode

### ISSUE THREAD

**Issue by grawity** [Cloudef/bemenu#72]
In `dmenu -l`, the items have a hanging indent that is as wide as the prompt or 'title':

![2019-11-25 091311 frost](https://user-images.githubusercontent.com/31021/69520115-668ec400-0f64-11ea-86d0-b672816a54ed.png)

In `bemenu -l`, they don't, and everything just looks slighly weird when it's glued to the screen edge:

![2019-11-25 091602 frost](https://user-images.githubusercontent.com/31021/69520131-73131c80-0f64-11ea-945b-d23ac790f42e.png)

(The `--prefix` option doesn't quite do the job; it just indents the text and not the background fill, and getting it to be exactly the right width can get annoying.)

**Comment by Cloudef** [comment]
I'd make this default rather than option to match dmenu.
