### ISSUE TITLE
display previous commands at the top of the menu

### ISSUE THREAD

**Issue by Soundtoxin** [Cloudef/bemenu#73]
Similar to `rofi`, it would be nice if launching something, such as `firefox`, from `bemenu` meant that on next launch it would be above commands you've never ran, and that the most frequently-ran thing was at the top. This is really handy if you've ran a long specific command that you'll want to run again later. Also just keeping a history in general so you can filter to old commands would be nice.

**Comment by Earnestly** [comment]
This is really a script that you could make.  `bemenu-run` exists as an implementation that mimics `dmenu` as closely as possible.

**Comment by Cloudef** [comment]
This would need a separate history file, or access to filesystem access history. It's out of scope of bemenu-run. It would be relatively simple to make such implementation either through shell script or editing bemenu-run.

**Comment by Soundtoxin** [comment]
Alright, good to know. Could anyone give me an example of how such a script might work?

**Comment by Cloudef** [comment]
Take a look at how `dmenu_run` and `dmenu_path` works. What you need to add is saving unique selections to history file and prepend that history to the list that gets feed to bemenu.
