### ISSUE TITLE
Bad font choice

### ISSUE THREAD

**Issue by Eluminae** [Cloudef/bemenu#74]
Hello there. I got a problem from 24h now. The bemenu seems to use a bad font. I don't have very much knowledge on this kind of things. 

Here's a screenshot 
![bemenu font problem](https://dav.misterbanal.net/pub/81de9588-eda8-4ede-8a49-c3c1c1c8dde8.png)

I'm on voidlinux, up to date. I don't think I installed something recently. Maybe this is an update issue from another package. Dunno

**Comment by Cloudef** [comment]
By default bemenu uses `Fixed` font. Maybe try selecting different font with the font switch. It could also be a fontconfig configuration issue (Fontconfig is very prone to breaking every update, in addition for being a thing that should have been replaced by something saner years ago). Note that `Fixed` is bitmap font which are disabled on many distros.

**Comment by Eluminae** [comment]
I really don't know what to do.

$ fc-match fixed
7x13-ISO8859-1.pcf.gz: "Fixed" "Regular"

I guess this font is causing the trouble

How can I force font ? Like this ?
$ echo -e "toot\ntiti" | bemenu -fn Free

I do not change anything

**Comment by Cloudef** [comment]
``` --fn                  defines the font to be used ('name [size]'). (wx)```
If this doesn't work, there is most likely something wrong with fontconfig. Recompiling bemenu may help as well.

**Comment by Cloudef** [comment]
https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/ has useful information for debugging fontconfig woes.

**Comment by Eluminae** [comment]
Ty a lot for your help. I'll have a look and debug all this :)
I'll post here solutions that helped me

**Comment by Earnestly** [comment]
@Cloudef Fixed may actually not be so wise anymore since harfbuzz dropped support for BDF/PCF formats.  Perhaps instead of `Fixed` a more common alternative such as `monospace` could be used?

**Comment by Eluminae** [comment]
What was the dmenu choice? It currently still is working on my machines.

**Comment by Earnestly** [comment]
dmenu uses `[monospace:size=10](https://git.suckless.org/dmenu/file/config.def.h.html#l7)`

**Comment by Eluminae** [comment]
I'm actually not sure it is a font issue anymore
$ echo -e "toto\ntiti" | bemenu -fn "monospace 10"
Do not change anything. The dmenu similar command change the displayed font but not dmenu. I still got squared font ^^
How can I debug the selected font ?

**Comment by Eluminae** [comment]
For personal futher analysis, the solution is somewhere here

```
Name                     Action    Version           New version            Download size
ImageMagick              update    7.0.9.7_1         7.0.9.8_1              49KB
alsa-lib                 update    1.2.1_1           1.2.1.2_1              355KB
alsa-lib-devel           update    1.2.1_1           1.2.1.2_1              67KB
base-files               update    0.140_8           0.140_10               51KB
calibre                  update    4.5.0_1           4.6.0_1                25MB
cups                     update    2.3.0_1           2.3.1_1                5096KB
cups-devel               update    2.3.0_1           2.3.1_1                35KB
fmt                      update    6.0.0_1           6.1.2_1                89KB
fribidi                  update    1.0.7_1           1.0.8_1                24KB
fribidi-devel            update    1.0.7_1           1.0.8_1                16KB
glib                     update    2.62.2_1          2.62.3_1               2111KB
glib-32bit               update    2.62.2_1          2.62.3_1               1021KB
imlib2                   update    1.6.0_1           1.6.1_1                170KB
iw                       update    5.3_1             5.4_1                  86KB
libcups                  update    2.3.0_1           2.3.1_1                219KB
libdav1d3                update    0.5.1_1           0.5.2_1                303KB
libdav1d3-32bit          update    0.5.1_1           0.5.2_1                256KB
libepoxy                 update    1.5.3_2           1.5.4_1                174KB
libepoxy-devel           update    1.5.3_2           1.5.4_1                119KB
libglib-devel            update    2.62.2_1          2.62.3_1               246KB
libmagick                update    7.0.9.7_1         7.0.9.8_1              2099KB
libmpdclient             update    2.16_1            2.17_1                 31KB
mit-krb5-libs            update    1.17_3            1.17.1_1               601KB
nghttp2                  update    1.39.2_1          1.40.0_1               636KB
nspr                     update    4.23_1            4.24_1                 114KB
nss                      update    3.47.1_1          3.48_1                 1280KB
oniguruma                update    6.9.3_1           6.9.4_1                135KB
pango                    update    1.42.4_5          1.44.7_1               170KB
pango-devel              update    1.42.4_5          1.44.7_1               125KB
pango-xft                update    1.42.4_5          1.44.7_1               14KB
perl-IO-stringy          update    2.111_2           2.112_1                25KB
python-PyQt5             update    5.13.0_1          5.13.2_1               2081KB
python-PyQt5-svg         update    5.13.0_1          5.13.2_1               22KB
python-PyQt5-webchannel  update    5.13.0_1          5.13.2_1               9.9KB
python-PyQt5-webengine   update    5.13.0_1          5.13.2_1               109KB
python-regex             update    2019.08.19_1      2019.12.9_1            227KB
python3-PyQt5            update    5.13.0_1          5.13.2_1               2216KB
python3-PyQt5-opengl     update    5.13.0_1          5.13.2_1               88KB
python3-PyQt5-quick      update    5.13.0_1          5.13.2_1               311KB
python3-PyQt5-sql        update    5.13.0_1          5.13.2_1               83KB
python3-PyQt5-webchannel update    5.13.0_1          5.13.2_1               11KB
python3-PyQt5-webengine  update    5.13.0_1          5.13.2_1               109KB
python3-parsedatetime    update    2.4_1             2.5_1                  29KB
rhash                    update    1.3.8_2           1.3.9_1                145KB
run-parts                update    4.9_1             4.9.1_1                9212B
shadow                   update    4.7_1             4.8_2                  228KB
x264                     update    20191129.2245_1   20191214.2245_1        613KB
x264-32bit               update    20191129.2245_1   20191214.2245_1        535KB
xmlsec1                  update    1.2.28_2          1.2.29_1               253KB
xvidcore                 update    1.3.5_1           1.3.6_1                193KB
xvidcore-32bit           update    1.3.5_1           1.3.6_1                191KB
yarn                     update    1.21.0_1          1.21.1_1               867KB
```

**Comment by Cloudef** [comment]
The font switch is `--fn` instead of `-fn`. As getopt doesn't support the - for long arguments. `-fn` means `-f -n` in getopt.

**Comment by Cloudef** [comment]
Bemenu uses pango for rendering on x11 and wayland, so that's a related package. `FC_DEBUG=4` may help with debugging font selection.

**Comment by Eluminae** [comment]
Is it possible to select fonts or additionals parameters using env variables ? I'd like to avoir setting `--ft blabla` everytime, in every scripts

**Comment by Eluminae** [comment]
If other users got the same problem, this is a fontconfig workarround

```
.config/fontconfig/
├── conf.avail
│   └── 70-no-fixed.conf
├── conf.d
│   └── 70-no-fixed.conf -> ../conf.avail/70-no-fixed.conf
```

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="pattern">
        <test qual="any" name="family"><string>fixed</string></test>
        <edit name="family" mode="assign" binding="same"><string>pango</string></edit>
    </match>
</fontconfig>
```

**Comment by Cloudef** [comment]
I'll update the bemenu to use monospace by default, which should fix this.

**Comment by Cloudef** [comment]
I made 0.3.0 release https://github.com/Cloudef/bemenu/releases/tag/0.3.0

**Comment by Eluminae** [comment]
You rocks. I update the void package :)

**Comment by Cloudef** [comment]
Note updated the release, as I forgot to bump the version in CMakeLists, thankfully somebody noticed that.

**Comment by Eluminae** [comment]
The root problem was a pango new release. It forced Void to downgrade the pango package see https://github.com/void-linux/void-packages/issues/17595

**Comment by Eluminae** [comment]
> Note updated the release, as I forgot to bump the version in CMakeLists, thankfully somebody noticed that.

You really made me think I made shit cause the checksum changed x))
