### ISSUE TITLE
bemenu does not show until I force sway to refresh display

### ISSUE THREAD

**Issue by k0ral** [Cloudef/bemenu#76]
On my side, when running `bemenu` on Sway, no menu is shown, and the terminal from which I ran it keeps the focus.
I've long thought it was something I misconfigured with respect to Wayland backend, but I recently noticed that forcing Sway to refresh display (using `swaymsg reload`, or using <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Fn</kbd> to switch back-and-forth between TTY and Sway), while `bemenu`is running, gets the menu to be correctly shown.
I don't know whether the issue is on Sway or bemenu side, but I am opening this issue to collect your opinion on what could possibly be happening that causes this behaviour, and if there's any way I can get useful debug logs to push the investigation further.

**Comment by tmccombs** [comment]
I've noticed this too, although sometimes it works and sometimes it doesn't.

**Comment by Cloudef** [comment]
Is this still a issue?

**Comment by k0ral** [comment]
The issue has vanished on my side, after upgrading my system (NixOs).
I'm fine with closing this issue, unless other users are still impacted.
