### ISSUE TITLE
bemenu suddenly stopped working

### ISSUE THREAD

**Issue by AdrienLemaire** [Cloudef/bemenu#79]
bemenu worked fine until yesterday, but suddenly doesn't do anything anymore.
```console
$ ls | bemenu

$
```

I cannot find any debug option in the bemenu manpages, so I have no idea what's happening and how to fix the issue.

```console
$ bemenu --version                                           │
bemenu v0.3.0 
$ pacman -Qs bemenu
local/bemenu 0.3.0-1
    Dynamic menu library and client program inspired by dmenu
    with support for wayland compositors
```
Running arch linux and sway 1:1.2-5 (wayland).

Any idea why this is happening?

**Comment by Cloudef** [comment]
Maybe #76 is related. Bisecting bemenu or sway can help here.
https://git-scm.com/docs/git-bisect

**Comment by zimbipw** [comment]
Having the same issue here. Downgrading to bemenu 0.1. brings back the menu.
pacman -Ss bemenu
community/bemenu 0.3.0-1 [Installiert: 0.1.0-1]

The temporary fix from https://github.com/Cloudef/bemenu/issues/76 using swaymsg reload dosn't work for me though.

**Comment by depate** [comment]
This is related to this [bug](https://bugs.archlinux.org/index.php?do=details&task_id=65087).

Seems to be that the wayland renderer was not compiled into the current package. 

#76 is most likely no related.

**Comment by escondida** [comment]
Actually, it's not just that -DCMAKE_OPTION, apparently. When building in a clean chroot (with wayland installed, naturally), even adding -DBEMENU_WAYLAND_RENDERER=ON to cmake's options doesn't help: it builds and installs the necessary .so, but when testing on weston it silently fails.

It's not a silent dependency on egl-wayland (though cmake does check for its presence). but since depate got it working when building (I assume) outside of a clean chroot, there's likely some kind of undocumented dependency thing going on here.

I guess I'll investigate this more tomorrow.

**Comment by escondida** [comment]
P.S.: Again, I'm testing in weston, since it's the reference implementation of a wayland compositor. If you want to build in a clean chroot on Arch when testing changes, use extra-x86_64-build from devtools.

**Comment by depate** [comment]
@escondida 
I'm no newbie to ArchLinux, but never had to deal with proper packaging or even package building. You're right: I did not use chroot. I have to read the [guides](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot) first. But I'm already working on it.

**Comment by escondida** [comment]
Yeah, it's nothing to worry about (-: . I never did either. It's definitely useful for making sure you don't wind up with unintended side-effects, such as automatically linking against something you have on your system that wasn't included in the dependencies.

**Comment by depate** [comment]
Ok. I am not completely sure whether I did everything correctly but:

- Modifying your `PKGBUILD` with `-DBEMENU_WAYLAND_RENDERER=ON` as additional `cmake` flag
- Running `extra-x86_64-build` with the modified PKGBUILD 
- Installing the resulting `*.pkg.tar.zst` via `pacman -U $pkg`

is working for me - with swaywm. 

Should I have run or installed the package in a `chroot` or isolated environment as well?

**Comment by AdrienLemaire** [comment]
Hmm, I tried the following, didn't work 
```console
$ yay -G bemenu && cd bemenu # PKGFILE 0.1.0 instead of 0.3.0-1? 
$ rm PKGFILE && curl 'https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/bemenu' > PKGBUILD
$ sed -i 's/\(cmake -DC.*\)$/\1 -DBEMENU_WAYLAND_RENDERER=ON/g' PKGBUILD
$ makepkg -si
==> Making package: bemenu 0.3.0-1 (Fri 10 Jan 2020 09:44:27 AM JST)
...
==> Verifying source file signatures with gpg...
    bemenu-0.3.0.tar.gz ... FAILED (unknown public key 0CBD2CD395613887)
==> ERROR: One or more PGP signatures could not be verified!
$ 
```
And I'm not understanding how I should use the extra-x86_64-build tool..

But removing bemenu and installing bemenu-git (with `-DBEMENU_X11_RENDERER=OFF -DBEMENU_WAYLAND_RENDERER=ON`) worked, so that's a relief :relieved:

**Comment by escondida** [comment]
Huh. Interesting. I'll try and get sway set up and see if it works there.

**Comment by colatkinson** [comment]
As a quick note: running 0.1.0-1 in weston also does not work. So there could be an upstream issue in addition to the Arch packaging problems.

@AdrienLemaire I ran into the same thing. I resolved it by running `gpg --recv-key 0CBD2CD395613887` to fetch the key. I did however run into a separate issue, namely a "makepkg: command not found" in the chroot. Let me know if anyone knows of a solution to that one.

**Comment by escondida** [comment]
Honestly, I've hardly ever seen this much activity on a bug in a day...usually it's like pulling teeth just to get any response at all. People love them some wayland, I guess!

I've gone ahead and pushed the rebuild, even though I can't see any positive result on Weston, and even though the current official upstream stance is that -DBMENU_WAYLAND_RENDERER=OFF (since that is the current default).

**Comment by Cloudef** [comment]
Weston isn't really supported, as bemenu uses the wlroots protocol for displaying itself in correct location. 

The wayland rendered was turned off by default by this change https://github.com/Cloudef/bemenu/pull/46 If you are packaging for distributions, you could also build with everything turned on and package the renderers separately so user can install what they want.

**Comment by Jpfonseca** [comment]
Current version of bemenu(0.3.0-2) seems to be working .

**Comment by Cloudef** [comment]
Closing this. Would be nice to be able to collect or sticky informative issues though.

**Comment by Cloudef** [comment]
Okay, pinning seems to work for closed issues too.

**Comment by Cloudef** [comment]
The build system now uses GNU make, to build wayland renderer you'd do
```sh
make wayland
```

Unpinning the issue as it's documented in README
