### ISSUE TITLE
Bemenu appears on all outputs with wayland

### ISSUE THREAD

**Issue by NilsIrl** [Cloudef/bemenu#80]
`-m` (`--monitor`) also do not work on Wayland

**Comment by Cloudef** [comment]
The `-m` option isn't implemented for the wayland renderer. 

I guess it could be implemented by modifying the section here:
https://github.com/Cloudef/bemenu/blob/master/lib/renderers/wayland/wayland.c#L279

`menu->monitor` will contain the value passed to `-m` by default it should be `0`. Bemenu for each monitor doesn't exist in X11, so I'm not sure how that should encoded if that behavior needs to be retained. 

X11 renderer also implements `set_monitor` function, that allows the monitor to be changed runtime, that might be bit more involved task for wayland. Not implementing it means that `bm_menu_set_monitor` needs to be called before the menu is rendered first time.

**Comment by NilsIrl** [comment]
> so I'm not sure how that should encoded if that behavior needs to be retained.

I can't find a reason to keep the feature/bug of it being on every monitor/output.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/178a58253a587092952a3b4a4aecc8f0940b5cb1
Maybe it works

**Comment by ppascher** [comment]
For me at least it was a nice feature to have bemenu shown on all outputs. It felt more natural to be looking at the monitor I want the application to open on while using bemenu. Especially with bemenu not being shown a layer above a fullscreen window (though this is possibly a bug with wlroots according to issue #81 ). Maybe it is possible to make it configurable?

**Comment by Cloudef** [comment]
maybe I could restore the old behavior with `-m -1` for wayland.
