### ISSUE TITLE
Visible Cursor Option

### ISSUE THREAD

**Issue by mehalter** [Cloudef/bemenu#82]
I have recently switched to bemenu from dmenu and am loving it! I was wondering if a feature could be added to enable a visible cursor in the input like dmenu. When moving around the input with C-a, C-e, arrow keys, it quickly becomes difficult to know where you are in the string.

**Comment by Cloudef** [comment]
Yes this is something that's missing from bemenu right now

**Comment by Cloudef** [comment]
Done with https://github.com/Cloudef/bemenu/commit/42eca376888dafe6dd1ed2bfe2a198c7b740bd2d
