### ISSUE TITLE
Resetting the filter cause a crash

### ISSUE THREAD

**Issue by hebrewd** [Cloudef/bemenu#85]
First, thank you for this project, the utility and the library are very useful and just works!

I'm using the bemenu library to write a simple file manager(can be found at gitlab.com/bennydarshan/bemenufm)

Once I reset the filter with bm_menu_set_filter(menu, NULL).
Attempting another search cause the menu to crash.

I've used gdb to try and dig into it, it seems like the it crashes for using strlen on the filter field itself... I looked through the code and tried to send various strings to the filter set and still got the same result.

If you can point me in the right direction, it will be very helpful.
Thanks again!

**Comment by Cloudef** [comment]
I assume uncommenting this will reproduce the issue?
https://gitlab.com/bennydarshan/bemenufm/blob/master/src/main.c#L33

I'll check it out.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/commit/7170c93f3a4821bf730a2b773aabd2f3132b4fe0
Maybe this fixes the issue for you

**Comment by hebrewd** [comment]
Yes, sorry for the hassle, I didn't mean for you to dig through my terrible code xD
I meant to compose a more condensed version of the issue, but you beat me to it :)

Thank you, I will compile the library with the commit and report the results!

**Comment by hebrewd** [comment]
Yes, I test it on a few installation just to be sure and it sure does the trick! thanks!
