### ISSUE TITLE
make install PREFIX=/usr screws sudo permissions

### ISSUE THREAD

**Issue by myelsukov** [Cloudef/bemenu#90]
This line: https://github.com/Cloudef/bemenu/blob/master/GNUmakefile#L101
sets `sudo` permissions to `0775` which renders it useless because `sudo` permissions should be `4775`

**Comment by Earnestly** [comment]
Incredible, I completely forgot that people actually install stuff via `make install` directly into their system instead of using a staging area or even package manager.

It would have to be modified to:

```make
install-bins:
	mkdir -p "$(DESTDIR)$(PREFIX)$(bindir)"
	-cp $(bins) "$(DESTDIR)$(PREFIX)$(bindir)"
	-for bin in $(bins); do chmod 0755 "$(DESTDIR)$(PREFIX)$(bindir)/$$bin"; done
```
