### ISSUE TITLE
bemenu list, delete the last characher in piped indput

### ISSUE THREAD

**Issue by kepet19** [Cloudef/bemenu#92]
# Sorry if this is not a concern too you 
```bash
[kkmp@Carbon ~]$ bemenu -v
bemenu v0.3.0

case "$(printf "a selected area\\nfull screen\\nkill recording " | bemenu -l 3 -i -p "Record which area?")" in
```
"nkill recording "
the space here^
after the recording word
the space is need, but it is not need in dmenu.

in dmenu you can just do "nkill recording" without the space.
```bash
case "$(printf "a selected area\\nfull screen\\nkill recording" | bemenu -l 3 -i -p "Record which area?")" in
```

if you do the same as dmenu in bemenu.
bemenu will only print "kill recordin" 

bemenu cuts of the last charter. 

# The script i need to put the space in.
```bash
#!/usr/bin/env sh

# This is bound to Shift+PrintScreen by default, requires wf-recorder and slurp. It lets you
# choose the kind of recording to take, including highlighting an area to record.

case "$(printf "a selected area\\nfull screen\\nkill recording " | bemenu -l 3 -i -p "Record which area?")" in
	"full screen") wf-recorder -f ~/recording_$(date +"%Y-%m-%d_%H:%M:%S.mp4") ;;
	"a selected area") wf-recorder -g "$(slurp)" -f ~/recording_$(date +"%Y-%m-%d_%H:%M:%S.mp4") ;;
	"kill recording") killall -s SIGINT wf-recorder ;;
esac
```

**Comment by Earnestly** [comment]
Why aren't you including the final terminating newline? Although the truncation is a bug.

**Comment by Cloudef** [comment]
Thank you for this bug report!
I fixed the null termination bug https://github.com/Cloudef/bemenu/commit/a89799a6b58b176a7eb48a1d9e2f935a7517d4ae

**Comment by kepet19** [comment]
Yeah if i had done that i would have worked both in dmenu and bemenu. that would have been smart.
thanks for the tip @Earnestly
