### ISSUE TITLE
Binary is incorrectly linked

### ISSUE THREAD

**Issue by ukch** [Cloudef/bemenu#97]
I have just compiled this on my Debian system, but cannot execute the binary, as it gives me the error `bemenu: error while loading shared libraries: libbemenu.so: cannot open shared object file: No such file or directory`

Here's the output of `ldd` on the `bemenu` binary and the `libbemenu.so` file:
```
$ ldd bemenu
	linux-vdso.so.1 (0x00007ffe337f6000)
	libbemenu.so => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f823827e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8238462000)
$ldd libbemenu.so
	linux-vdso.so.1 (0x00007ffc646b7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007facdd585000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007facdd3c5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007facdd5b2000)
```
Note that the `bemenu` binary is unable to find the `libbemenu.so` library, even though they are in the same directory.

**Comment by Cloudef** [comment]
use `LD_LIBRARY_PATH=.` if you want it o load from same directory.
