### ISSUE TITLE
keypresses lost/eaten occasionally

### ISSUE THREAD

**Issue by Soundtoxin** [Cloudef/bemenu#98]
If I open bemenu-run and type stuff, I lose two letters. I don't know the exact interval, and it's not always the same letters. I tried to type "the quick brown fox jumps over the lazy dog" two times. The first time I lost the "wn" in "brown". The second time I think I lost part of the word "jumps" so it said "jus". It's the sorta thing that could drive a man crazy.
I'm on version 0.3.0 from the NixOS repos, so apologies if this bug has already been fixed in a later version. I searched the issues for "keypress" and saw nothing.
I believe this happens with bemenu in general, by the way. I also have a clipboard script that uses it and seems to lose keypresses, so it's not specific to the run command.
I'm using Sway (wayland), if that matters.

**Comment by Cloudef** [comment]
Does this happen only during startup of bemenu, or anytime? For startups keyboard grab could help, but that code is currently disabled, since there is no keyboard handling during input read, and if stdin isn't ever closed, it could easily softlock your graphical env.

**Comment by Soundtoxin** [comment]
I'm not sure if I'm understanding the question. It happens every time I do something with bemenu, I can reproduce the issue. I lose tons of letters. It's not just the first letters typed, and it's not just the first time I launch bemenu in my session. If you think you might've really missed typing some letters, I could see someone not noticing it, so I would recommend typing something long and paying attention to what you're hitting to reproduce it.
I just did a little testing and it might only happen when you're typing over a certain speed... When I type really slowly it doesn't seem to happen. I am probably typing a little over 100wpm but no more than 120wpm in these tests where it's having issues.

**Comment by Cloudef** [comment]
Most likely the wayland "event loop" (if you can even call it that) code is not optimal. Might also be related to key repeating maybe. https://github.com/Cloudef/bemenu/blob/1873f7460fe9e99c405f99f97f82ae67f783b48f/lib/renderers/wayland/wayland.c#L17-L53 I don't have wayland setup myself currently so I can't check this right now.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/bemenu/blob/1873f7460fe9e99c405f99f97f82ae67f783b48f/lib/renderers/wayland/wayland.c#L34-L35
Can you try changing the number 16 in these two lines to 1?
What this function is supposed to do, is block until whatever event related to wayland comes in, and only continue after that. I'm not sure why it's waiting for max 16 events right now, but this might very well eat input.

**Comment by Soundtoxin** [comment]
I've never built (unpackaged) things from source on NixOS and it's looking to be a pain, so I might not be able to figure this out any time soon. I cloned the repo, made the changes in that file, and ran `make`, but then was greeted with some errors.
```
cc -g -O2 -Wall -Wextra -Wpedantic -Wformat=2 -Wstrict-aliasing=3 -Wstrict-overflow=5 -Wstack-usage=12500 -Wfloat-equal -Wcast-align -Wpointer-arith -Wchar-subscripts -Warray-bounds=2 -Wno-unknown-warning-option -std=c99 -D_FORTIFY_SOURCE=2 -DBM_VERSION=\"0.4.0\" -DBM_PLUGIN_VERSION=\"0.4.0-1873f7460fe9e99c405f99f97f82ae67f783b48f\" -DINSTALL_LIBDIR=\"/usr/local/lib\" -D_DEFAULT_SOURCE -Ilib   -c lib/3rdparty/cdl.c  -o cdl.a
make: cc: Command not found
make: *** [GNUmakefile:36: cdl.a] Error 127

**Comment by Cloudef** [comment]
@Soundtoxin interesting, nixos doesn't have POSIX compatible compiler binary in path? Or maybe you don't have compiler installed? If you have and know where it is, you can point to it by setting the CC env variable manually and make should pick it up.

**Comment by Cloudef** [comment]
https://nixos.org/nixos/nix-pills/developing-with-nix-shell.html
Maybe this helps

**Comment by Soundtoxin** [comment]
> You should be able to enter into the bemenu's packaging environment with `nix-shell bemenu` I think. This means all dependencies should be available and env variables set for you. Maybe it clones source for you too

```
brad@anpan:~/ > nix-shell bemenu
error: getting status of '/home/brad/bemenu': No such file or directory
```
brad@anpan:~/ > cd Downloads 
brad@anpan:~/Downloads/ > nix-shell bemenu
error: opening file '/home/brad/Downloads/bemenu/default.nix': No such file or directory
```
I don't really know what I'm doing, unfortunately, but it seems this nix-shell workflow probably requires more setup. I'm not sure if I have the energy to figure all this out, but this bug is extremely annoying, so I'd like to do something.

**Comment by Cloudef** [comment]
I think best is to ask nix community (irc channel or such?). They most likely can tell you the best way to compile projects. If all else fails, you can always install more traditional distro into chroot or vm.

**Comment by lheckemann** [comment]
@Soundtoxin you can enter a shell with the appropriate environment for building bemenu (the version in your "standard" nixpkgs) using `nix-shell '<nixpkgs>' -A bemenu`.

I haven't had this issue myself. I've opened a PR to update to 0.4.1 (https://github.com/NixOS/nixpkgs/pull/87594), you can use `nix run -f https://github.com/mayflower/nixpkgs/archive/bemenu-bump.tar.gz bemenu` to get a shell with that bemenu build until the branch is deleted (after merging :) )

**Comment by Soundtoxin** [comment]
> I haven't had this issue myself.

I think it's highly likely you just haven't noticed. If you think you missed a key, or if you type slow enough you may think everything is fine.

i believe the thing I was asked to test was tested by someone in another issue now anyway, so I'm not sure what I'd do at this point.

**Comment by Soundtoxin** [comment]
>you can use `nix run -f https://github.com/mayflower/nixpkgs/archive/bemenu-bump.tar.gz bemenu` to get a shell with that bemenu build until the branch is deleted (after merging :) )
I've just done this and tried out bemenu with my usual command from it. At first it seems better, but the issue is definitely still there. Perhaps it happens less often, but I'm still seeing it if I just try typing out sentences in the prompt, I start getting missing characters after a bit of typing into it.

**Comment by fancycade** [comment]
Hi, I've been able to replicate this issue for every single release. My setup is Sway inside of a Qemu vm.

After some messing around I found that this line of code seems to be causing the issue.

https://github.com/Cloudef/bemenu/blob/master/lib/renderers/wayland/registry.c#L110

Currently looks this:
```
    input->sym = (state == WL_KEYBOARD_KEY_STATE_PRESSED ? sym : XKB_KEY_NoSymbol);
    input->code = (state == WL_KEYBOARD_KEY_STATE_PRESSED ? key + 8 : 0);
```

I changed it to this:
```
    input->sym = sym;
    input->code = key + 8;
```

This solves the problem of keys being eaten, but it introduces a new problem where occasionally keys are repeated. I believe these are related. Either way I'm assuming this has something to do with the key being acted upon asynchronously from when the key is pressed or released.

Wish I had a fix, but I'm happy to test out any patches.

**Comment by Cloudef** [comment]
>This solves the problem of keys being eaten, but it introduces a new problem where occasionally keys are repeated. I believe these are related. Either way I'm assuming this has something to do with the key being acted upon asynchronously from when the key is pressed or released.

This seems to be in line with my original suspicion. The event loop doesn't properly act on each key event, probably some of the wl_dispatches, throws away the key event.

**Comment by Soundtoxin** [comment]
It would be nice to have a release that includes this soon. I'm actually avoiding bemenu until this is fixed, but I miss the speed it has over wofi.

**Comment by joanbm** [comment]
This is not yet fully fixed, it still happens if you type fast:

https://user-images.githubusercontent.com/519004/182721004-d4a0fb4d-2bfd-4160-9c9b-8e9bff1b1fe1.mp4

In this video, I type "htop" (as shown by `wshowkeys` , but bemenu doesn't pick up the "t".

I think #135 is incomplete, it handles the case of a key press and key release event happening in the same event loop iteration, not the case of two key presses occurring in the same event loop iteration.

**Comment by Soundtoxin** [comment]
Typing normally even at high speeds I don't see the issue, but if I press keys at the same time I do notice they don't all appear, and I have NKRO, so they probably should. If in typing htop you were to press the h and t at the same time, that could be the issue.

**Comment by joanbm** [comment]
It's a somewhat obscure scenario but it happens to me sometimes due to muscle memory. I know that e.g. to open Firefox I need to open bemenu and press "fi"+Enter, and I have done this so many times that my "f" and "i" keypresses are extremely close to each other and sometimes bemenu misses them (as you noted it depends on how close to each other your presses are rather than WPM).

WIP fix: https://github.com/joanbm/bemenu/tree/fix-missed-consecutive-keypresses
